/* ============================================================
   SATZBAU-BANK — die Verbstellungs-Leiter (Phase 4, 04.09.)

   5 Stufen à 25 Sätze, komplett offline (kostenlos, streak-
   sicher). Jeder Satz: { ko, teile } — die koreanische
   Übersetzung steht in der Übung SCHON VOR dem Bauen (Feedback
   Haein 04.09.: sie soll wissen, WAS sie sagt, und wirklich nur
   die Anordnung lernen). Die teile sind BAUSTEINE — Wortgruppen
   bleiben zusammen. Der ERSTE Baustein wird vorgelegt (nimmt
   Mehrdeutigkeit raus); Satzzeichen werden in der Übung von den
   Kacheln entfernt (sonst verraten sie die Position).

   Kuratiert im A2-Alltagswortschatz; die Leiter folgt dem
   Kernkampf koreanischer Lernender: Verb an Position 2 (im
   Koreanischen steht es am Ende!) -> Klammer -> Nebensatz.
   ============================================================ */

export const SATZBAU_STUFEN = [
  {
    id: 1,
    titel: 'Hauptsatz',
    ko: '기본 문장',
    tipp: '동사는 항상 두 번째 자리에 와요! (한국어와 달리 문장 끝이 아니에요)',
    saetze: [
      { ko: '나는 아침마다 커피를 마셔요.', teile: ['Ich', 'trinke', 'jeden Morgen', 'Kaffee.'] },
      { ko: '우리는 베를린에 살아요.', teile: ['Wir', 'wohnen', 'in Berlin.'] },
      { ko: '해인은 매일 독일어를 공부해요.', teile: ['Haein', 'lernt', 'jeden Tag', 'Deutsch.'] },
      { ko: '수업은 8시에 시작해요.', teile: ['Der Kurs', 'beginnt', 'um acht Uhr.'] },
      { ko: '나는 국수를 즐겨 먹어요.', teile: ['Ich', 'esse', 'gern', 'Nudeln.'] },
      { ko: '우리 오빠는 병원에서 일해요.', teile: ['Mein Bruder', 'arbeitet', 'im Krankenhaus.'] },
      { ko: '아이들은 공원에서 놀아요.', teile: ['Die Kinder', 'spielen', 'im Park.'] },
      { ko: '나는 빵과 우유를 사요.', teile: ['Ich', 'kaufe', 'Brot', 'und Milch.'] },
      { ko: '오늘 날씨가 좋아요.', teile: ['Das Wetter', 'ist', 'heute', 'schön.'] },
      { ko: '그는 버스를 타고 회사에 가요.', teile: ['Er', 'fährt', 'mit dem Bus', 'zur Arbeit.'] },
      { ko: '우리 엄마는 요리를 아주 잘해요.', teile: ['Meine Mutter', 'kocht', 'sehr gut.'] },
      { ko: '나는 저녁에 TV를 봐요.', teile: ['Ich', 'sehe', 'abends', 'fern.'] },
      { ko: '그 집에는 방이 세 개 있어요.', teile: ['Die Wohnung', 'hat', 'drei Zimmer.'] },
      { ko: '우리는 일요일에 영화관에 가요.', teile: ['Wir', 'gehen', 'am Sonntag', 'ins Kino.'] },
      { ko: '그녀는 책 읽기를 좋아해요.', teile: ['Sie', 'liest', 'gern', 'Bücher.'] },
      { ko: '나는 새 펜이 필요해요.', teile: ['Ich', 'brauche', 'einen neuen Stift.'] },
      { ko: '기차는 시간이 아주 정확해요.', teile: ['Der Zug', 'ist', 'sehr pünktlich.'] },
      { ko: '나는 친구에게 이메일을 써요.', teile: ['Ich', 'schreibe', 'eine E-Mail', 'an meine Freundin.'] },
      { ko: '음식이 정말 맛있어요.', teile: ['Das Essen', 'schmeckt', 'wirklich', 'lecker.'] },
      { ko: '우리는 오늘 피크닉을 해요.', teile: ['Wir', 'machen', 'heute', 'ein Picknick.'] },
      { ko: '나는 그 질문을 이해 못 해요.', teile: ['Ich', 'verstehe', 'die Frage', 'nicht.'] },
      { ko: '내 휴대폰이 아쉽게도 고장 났어요.', teile: ['Mein Handy', 'ist', 'leider', 'kaputt.'] },
      { ko: '시험은 30분 걸려요.', teile: ['Die Prüfung', 'dauert', 'dreißig Minuten.'] },
      { ko: '나는 역까지 택시를 타요.', teile: ['Ich', 'nehme', 'ein Taxi', 'zum Bahnhof.'] },
      { ko: '그는 세 가지 언어를 말해요.', teile: ['Er', 'spricht', 'drei Sprachen.'] },
    ],
  },
  {
    id: 2,
    titel: 'Umgedreht',
    ko: '뒤집기 (Inversion)',
    tipp: '시간·장소가 맨 앞에 오면? 동사는 그대로 두 번째, 주어가 동사 뒤로 가요!',
    saetze: [
      { ko: '오늘 나는 영화관에 가요.', teile: ['Heute', 'gehe', 'ich', 'ins Kino.'] },
      { ko: '월요일에 수업이 시작해요.', teile: ['Am Montag', 'beginnt', 'der Kurs.'] },
      { ko: '내일 나는 할머니를 뵈러 가요.', teile: ['Morgen', 'besuche', 'ich', 'meine Oma.'] },
      { ko: '여름에 우리는 바다에 가요.', teile: ['Im Sommer', 'fahren', 'wir', 'ans Meer.'] },
      { ko: '저녁에 나는 가족을 위해 요리해요.', teile: ['Abends', 'koche', 'ich', 'für meine Familie.'] },
      { ko: '8시에 우리는 함께 아침을 먹어요.', teile: ['Um acht Uhr', 'frühstücken', 'wir', 'zusammen.'] },
      { ko: '퇴근 후에 나는 친구들을 만나요.', teile: ['Nach der Arbeit', 'treffe', 'ich', 'meine Freunde.'] },
      { ko: '아쉽게도 나는 시간이 없어요.', teile: ['Leider', 'habe', 'ich', 'keine Zeit.'] },
      { ko: '다음 주에 나는 시험을 봐요.', teile: ['Nächste Woche', 'schreibe', 'ich', 'eine Prüfung.'] },
      { ko: '서울에는 우리 부모님이 사세요.', teile: ['In Seoul', 'wohnen', 'meine Eltern.'] },
      { ko: '내일은 비가 올지도 몰라요.', teile: ['Vielleicht', 'regnet', 'es', 'morgen.'] },
      { ko: '주말에 나는 늦잠을 자요.', teile: ['Am Wochenende', 'schlafe', 'ich', 'lange.'] },
      { ko: '겨울에는 아주 추워요.', teile: ['Im Winter', 'ist', 'es', 'sehr kalt.'] },
      { ko: '그다음에 우리는 커피를 마셔요.', teile: ['Danach', 'trinken', 'wir', 'einen Kaffee.'] },
      { ko: '1년 전부터 나는 독일어를 배우고 있어요.', teile: ['Seit einem Jahr', 'lerne', 'ich', 'Deutsch.'] },
      { ko: '생일에 그녀는 꽃을 받아요.', teile: ['Zum Geburtstag', 'bekommt', 'sie', 'Blumen.'] },
      { ko: '가끔 나는 초콜릿을 먹어요.', teile: ['Manchmal', 'esse', 'ich', 'Schokolade.'] },
      { ko: '저녁에 우리는 영화를 봐요.', teile: ['Am Abend', 'sehen', 'wir', 'einen Film.'] },
      { ko: '쉬는 시간에 나는 빵을 먹어요.', teile: ['In der Pause', 'esse', 'ich', 'ein Brötchen.'] },
      { ko: '저기에 정류장이 있어요.', teile: ['Dort', 'ist', 'die Haltestelle.'] },
      { ko: '매일 나는 10분씩 연습해요.', teile: ['Jeden Tag', 'übe', 'ich', 'zehn Minuten.'] },
      { ko: '먼저 우리는 숙제를 해요.', teile: ['Zuerst', 'machen', 'wir', 'die Hausaufgaben.'] },
      { ko: '내일은 해가 나면 좋겠어요.', teile: ['Hoffentlich', 'scheint', 'morgen', 'die Sonne.'] },
      { ko: '비가 오면 우리는 집에 있어요.', teile: ['Bei Regen', 'bleiben', 'wir', 'zu Hause.'] },
      { ko: '시험을 위해 그녀는 매일 저녁 공부해요.', teile: ['Für die Prüfung', 'lernt', 'sie', 'jeden Abend.'] },
    ],
  },
  {
    id: 3,
    titel: 'Modalverben',
    ko: '조동사 괄호',
    tipp: '조동사(kann, muss, will…)는 두 번째 자리, 본동사 원형은 맨 끝! 괄호처럼 감싸요.',
    saetze: [
      { ko: '나는 오늘 갈 수 없어요.', teile: ['Ich', 'kann', 'heute', 'nicht', 'kommen.'] },
      { ko: '우리는 지금 가야 해요.', teile: ['Wir', 'müssen', 'jetzt', 'gehen.'] },
      { ko: '그는 독일어를 배우고 싶어 해요.', teile: ['Er', 'will', 'Deutsch', 'lernen.'] },
      { ko: '나 좀 도와줄 수 있어요?', teile: ['Kannst', 'du', 'mir', 'helfen?'] },
      { ko: '그녀는 커피를 마시고 싶어 해요.', teile: ['Sie', 'möchte', 'einen Kaffee', 'trinken.'] },
      { ko: '나는 내일 일찍 일어나야 해요.', teile: ['Ich', 'muss', 'morgen früh', 'aufstehen.'] },
      { ko: '여기서는 담배를 피우면 안 돼요.', teile: ['Man', 'darf', 'hier', 'nicht', 'rauchen.'] },
      { ko: '방을 하나 예약하고 싶어요.', teile: ['Ich', 'möchte', 'ein Zimmer', 'reservieren.'] },
      { ko: '물을 더 많이 마셔야 해요.', teile: ['Du', 'sollst', 'mehr Wasser', 'trinken.'] },
      { ko: '우리는 금요일에 만날 수 있어요.', teile: ['Wir', 'können', 'uns', 'am Freitag', 'treffen.'] },
      { ko: '나는 여름에 한국에 가고 싶어요.', teile: ['Ich', 'will', 'im Sommer', 'nach Korea', 'fliegen.'] },
      { ko: '너희는 우리 집에서 자도 돼요.', teile: ['Ihr', 'könnt', 'bei uns', 'übernachten.'] },
      { ko: '나는 수영을 잘할 수 있어요.', teile: ['Ich', 'kann', 'gut', 'schwimmen.'] },
      { ko: '예약을 해야 하나요?', teile: ['Muss', 'ich', 'einen Termin', 'machen?'] },
      { ko: '그녀는 오늘 더 오래 자도 돼요.', teile: ['Sie', 'darf', 'heute', 'länger', 'schlafen.'] },
      { ko: '우리는 파티를 하고 싶어요.', teile: ['Wir', 'wollen', 'eine Party', 'machen.'] },
      { ko: '카드로 계산하고 싶어요.', teile: ['Ich', 'möchte', 'mit Karte', 'bezahlen.'] },
      { ko: '그는 아쉽게도 같이 못 가요.', teile: ['Er', 'kann', 'leider', 'nicht', 'mitkommen.'] },
      { ko: '그 글을 한 번 더 읽어야 해요.', teile: ['Du', 'musst', 'den Text', 'noch einmal', 'lesen.'] },
      { ko: '우리는 계산을 하고 싶어요.', teile: ['Wir', 'möchten', 'die Rechnung', 'bezahlen.'] },
      { ko: '나는 사장님께 전화해야 해요.', teile: ['Ich', 'soll', 'den Chef', 'anrufen.'] },
      { ko: '창문을 열어도 될까요?', teile: ['Kann', 'ich', 'das Fenster', 'öffnen?'] },
      { ko: '여기서 잠깐 기다리셔야 해요.', teile: ['Sie', 'müssen', 'hier', 'kurz', 'warten.'] },
      { ko: '나는 아이스크림을 먹으면 안 돼요.', teile: ['Ich', 'darf', 'kein Eis', 'essen.'] },
      { ko: '우리는 토요일에 등산하고 싶어요.', teile: ['Wir', 'wollen', 'am Samstag', 'wandern.'] },
    ],
  },
  {
    id: 4,
    titel: 'Perfekt',
    ko: '과거 괄호 (Perfekt)',
    tipp: 'haben/sein은 두 번째 자리, Partizip(ge-…)은 맨 끝! 또 괄호예요.',
    saetze: [
      { ko: '나는 어제 피자를 먹었어요.', teile: ['Ich', 'habe', 'gestern', 'Pizza', 'gegessen.'] },
      { ko: '우리는 부산에 갔어요.', teile: ['Wir', 'sind', 'nach Busan', 'gefahren.'] },
      { ko: '그녀는 책을 읽었어요.', teile: ['Sie', 'hat', 'ein Buch', 'gelesen.'] },
      { ko: '그는 오늘 늦게 일어났어요.', teile: ['Er', 'ist', 'heute', 'spät', 'aufgestanden.'] },
      { ko: '나는 할머니를 방문했어요.', teile: ['Ich', 'habe', 'meine Oma', 'besucht.'] },
      { ko: '잘 잤어요?', teile: ['Hast', 'du', 'gut', 'geschlafen?'] },
      { ko: '우리는 영화를 봤어요.', teile: ['Wir', 'haben', 'einen Film', 'gesehen.'] },
      { ko: '나는 집에 있었어요.', teile: ['Ich', 'bin', 'zu Hause', 'geblieben.'] },
      { ko: '그들은 많이 웃었어요.', teile: ['Sie', 'haben', 'viel', 'gelacht.'] },
      { ko: '나는 숙제를 했어요.', teile: ['Ich', 'habe', 'die Hausaufgaben', 'gemacht.'] },
      { ko: '기차가 제시간에 도착했어요.', teile: ['Der Zug', 'ist', 'pünktlich', 'angekommen.'] },
      { ko: '우리는 식당에서 먹었어요.', teile: ['Wir', 'haben', 'im Restaurant', 'gegessen.'] },
      { ko: '나는 선물을 샀어요.', teile: ['Ich', 'habe', 'ein Geschenk', 'gekauft.'] },
      { ko: '비행기를 타 본 적 있어요?', teile: ['Bist', 'du', 'schon einmal', 'geflogen?'] },
      { ko: '그는 버스를 놓쳤어요.', teile: ['Er', 'hat', 'den Bus', 'verpasst.'] },
      { ko: '나는 오늘 독일어를 연습했어요.', teile: ['Ich', 'habe', 'heute', 'Deutsch', 'geübt.'] },
      { ko: '우리는 공원에서 산책했어요.', teile: ['Wir', 'sind', 'im Park', 'spazieren gegangen.'] },
      { ko: '그녀는 일찍 잠들었어요.', teile: ['Sie', 'ist', 'früh', 'eingeschlafen.'] },
      { ko: '나는 너에게 메시지를 보냈어요.', teile: ['Ich', 'habe', 'dir', 'eine Nachricht', 'geschrieben.'] },
      { ko: '주말에 뭐 했어요?', teile: ['Was', 'hast', 'du', 'am Wochenende', 'gemacht?'] },
      { ko: '우리는 호텔을 금방 찾았어요.', teile: ['Wir', 'haben', 'das Hotel', 'schnell', 'gefunden.'] },
      { ko: '나는 자전거를 타고 갔어요.', teile: ['Ich', 'bin', 'mit dem Rad', 'gefahren.'] },
      { ko: '그는 나를 많이 도와줬어요.', teile: ['Er', 'hat', 'mir', 'sehr', 'geholfen.'] },
      { ko: '나는 열쇠를 잃어버렸어요.', teile: ['Ich', 'habe', 'den Schlüssel', 'verloren.'] },
      { ko: '그녀는 케이크를 구웠어요.', teile: ['Sie', 'hat', 'einen Kuchen', 'gebacken.'] },
    ],
  },
  {
    id: 5,
    titel: 'weil & dass',
    ko: '종속절 (동사 끝으로!)',
    tipp: 'weil/dass 뒤에는 동사가 문장 맨 끝으로 가요 — 드디어 한국어처럼!',
    saetze: [
      { ko: '아파서 나는 집에 있어요.', teile: ['Ich bleibe zu Hause,', 'weil', 'ich', 'krank', 'bin.'] },
      { ko: '나는 독일어가 어렵다고 생각해요.', teile: ['Ich denke,', 'dass', 'Deutsch', 'schwer', 'ist.'] },
      { ko: '내일이 생일이라서 그녀는 기뻐해요.', teile: ['Sie freut sich,', 'weil', 'morgen', 'ihr Geburtstag', 'ist.'] },
      { ko: '네가 올 수 있으면 좋겠어요.', teile: ['Ich hoffe,', 'dass', 'du', 'kommen', 'kannst.'] },
      { ko: '비가 와서 우리는 택시를 타요.', teile: ['Wir nehmen ein Taxi,', 'weil', 'es', 'regnet.'] },
      { ko: '그는 시간이 없다고 말해요.', teile: ['Er sagt,', 'dass', 'er', 'keine Zeit', 'hat.'] },
      { ko: '곧 시험이라서 나는 매일 공부해요.', teile: ['Ich lerne jeden Tag,', 'weil', 'die Prüfung', 'bald', 'ist.'] },
      { ko: '그 식당이 오늘 문을 닫은 것 같아요.', teile: ['Ich glaube,', 'dass', 'das Restaurant', 'heute', 'geschlossen', 'ist.'] },
      { ko: '일찍 일어나서 그녀는 피곤해요.', teile: ['Sie ist müde,', 'weil', 'sie', 'früh', 'aufgestanden', 'ist.'] },
      { ko: '네가 요리를 잘하는 걸 알아요.', teile: ['Ich weiß,', 'dass', 'du', 'gut', 'kochst.'] },
      { ko: '추워서 우리는 안에 있어요.', teile: ['Wir bleiben drinnen,', 'weil', 'es', 'kalt', 'ist.'] },
      { ko: '그는 기차가 연착된다고 써요.', teile: ['Er schreibt,', 'dass', 'der Zug', 'Verspätung', 'hat.'] },
      { ko: '네가 있어서 나는 행복해요.', teile: ['Ich bin glücklich,', 'weil', 'du', 'da', 'bist.'] },
      { ko: '그녀는 내일 전화한다고 해요.', teile: ['Sie sagt,', 'dass', 'sie', 'morgen', 'anruft.'] },
      { ko: '채식주의자라서 나는 고기를 안 먹어요.', teile: ['Ich esse kein Fleisch,', 'weil', 'ich', 'Vegetarierin', 'bin.'] },
      { ko: '나는 이 도시가 예쁘다고 생각해요.', teile: ['Ich finde,', 'dass', 'die Stadt', 'schön', 'ist.'] },
      { ko: '아직 일해야 해서 그는 늦게 와요.', teile: ['Er kommt später,', 'weil', 'er', 'noch', 'arbeiten', 'muss.'] },
      { ko: '날씨가 계속 좋으면 좋겠어요.', teile: ['Ich hoffe,', 'dass', 'das Wetter', 'gut', 'bleibt.'] },
      { ko: '시험에 합격해서 우리는 오늘 파티를 해요.', teile: ['Wir feiern heute,', 'weil', 'wir', 'die Prüfung', 'bestanden', 'haben.'] },
      { ko: '그녀는 시험이 쉬웠다고 생각해요.', teile: ['Sie glaubt,', 'dass', 'der Test', 'leicht', 'war.'] },
      { ko: '질문이 있어서 전화해요.', teile: ['Ich rufe an,', 'weil', 'ich', 'eine Frage', 'habe.'] },
      { ko: '그는 우리가 더 일찍 와야 한다고 해요.', teile: ['Er meint,', 'dass', 'wir', 'früher', 'kommen', 'sollen.'] },
      { ko: '여행하고 싶어서 나는 돈을 모아요.', teile: ['Ich spare Geld,', 'weil', 'ich', 'reisen', 'möchte.'] },
      { ko: '독일에서 공부하고 싶어서 그녀는 열심히 공부해요.', teile: ['Sie lernt viel,', 'weil', 'sie', 'in Deutschland', 'studieren', 'will.'] },
      { ko: '우리는 택시가 필요할 것 같아요.', teile: ['Ich denke,', 'dass', 'wir', 'ein Taxi', 'brauchen.'] },
    ],
  },
]
