/* ============================================================
   SATZBAU-BANK — die Verbstellungs-Leiter (Phase 4, 04.09.)

   5 Stufen à 25 Sätze, komplett offline (kostenlos, streak-
   sicher). Jeder Satz ist ein Array von BAUSTEINEN — Wortgruppen
   bleiben zusammen (weniger Mehrdeutigkeit, klareres Lernen).
   Der ERSTE Baustein wird in der Übung vorgelegt: das nimmt
   die Mehrdeutigkeit raus (z. B. Inversion: „Heute …" vorgeben)
   und lenkt den Blick auf den Kern — wo steht das Verb?

   Kuratiert im A2-Alltagswortschatz; die Leiter folgt dem
   Kernkampf koreanischer Lernender: Verb an Position 2 (im
   Koreanischen steht es am Ende!) -> Klammer -> Nebensatz.
   ============================================================ */

export const SATZBAU_STUFEN = [
  {
    id: 1,
    titel: 'Hauptsatz',
    ko: '기본 문장',
    tipp: '동사는 항상 두 번째 자리에 와요! (한국어와 달리 문장 끝이 아니에요)',
    saetze: [
      ['Ich', 'trinke', 'jeden Morgen', 'Kaffee.'],
      ['Wir', 'wohnen', 'in Berlin.'],
      ['Haein', 'lernt', 'jeden Tag', 'Deutsch.'],
      ['Der Kurs', 'beginnt', 'um acht Uhr.'],
      ['Ich', 'esse', 'gern', 'Nudeln.'],
      ['Mein Bruder', 'arbeitet', 'im Krankenhaus.'],
      ['Die Kinder', 'spielen', 'im Park.'],
      ['Ich', 'kaufe', 'Brot', 'und Milch.'],
      ['Das Wetter', 'ist', 'heute', 'schön.'],
      ['Er', 'fährt', 'mit dem Bus', 'zur Arbeit.'],
      ['Meine Mutter', 'kocht', 'sehr gut.'],
      ['Ich', 'sehe', 'abends', 'fern.'],
      ['Die Wohnung', 'hat', 'drei Zimmer.'],
      ['Wir', 'gehen', 'am Sonntag', 'ins Kino.'],
      ['Sie', 'liest', 'gern', 'Bücher.'],
      ['Ich', 'brauche', 'einen neuen Stift.'],
      ['Der Zug', 'ist', 'sehr pünktlich.'],
      ['Ich', 'schreibe', 'eine E-Mail', 'an meine Freundin.'],
      ['Das Essen', 'schmeckt', 'wirklich', 'lecker.'],
      ['Wir', 'machen', 'heute', 'ein Picknick.'],
      ['Ich', 'verstehe', 'die Frage', 'nicht.'],
      ['Mein Handy', 'ist', 'leider', 'kaputt.'],
      ['Die Prüfung', 'dauert', 'dreißig Minuten.'],
      ['Ich', 'nehme', 'ein Taxi', 'zum Bahnhof.'],
      ['Er', 'spricht', 'drei Sprachen.'],
    ],
  },
  {
    id: 2,
    titel: 'Umgedreht',
    ko: '뒤집기 (Inversion)',
    tipp: '시간·장소가 맨 앞에 오면? 동사는 그대로 두 번째, 주어가 동사 뒤로 가요!',
    saetze: [
      ['Heute', 'gehe', 'ich', 'ins Kino.'],
      ['Am Montag', 'beginnt', 'der Kurs.'],
      ['Morgen', 'besuche', 'ich', 'meine Oma.'],
      ['Im Sommer', 'fahren', 'wir', 'ans Meer.'],
      ['Abends', 'koche', 'ich', 'für meine Familie.'],
      ['Um acht Uhr', 'frühstücken', 'wir', 'zusammen.'],
      ['Nach der Arbeit', 'treffe', 'ich', 'meine Freunde.'],
      ['Leider', 'habe', 'ich', 'keine Zeit.'],
      ['Nächste Woche', 'schreibe', 'ich', 'eine Prüfung.'],
      ['In Seoul', 'wohnen', 'meine Eltern.'],
      ['Vielleicht', 'regnet', 'es', 'morgen.'],
      ['Am Wochenende', 'schlafe', 'ich', 'lange.'],
      ['Im Winter', 'ist', 'es', 'sehr kalt.'],
      ['Danach', 'trinken', 'wir', 'einen Kaffee.'],
      ['Seit einem Jahr', 'lerne', 'ich', 'Deutsch.'],
      ['Zum Geburtstag', 'bekommt', 'sie', 'Blumen.'],
      ['Manchmal', 'esse', 'ich', 'Schokolade.'],
      ['Am Abend', 'sehen', 'wir', 'einen Film.'],
      ['In der Pause', 'esse', 'ich', 'ein Brötchen.'],
      ['Dort', 'ist', 'die Haltestelle.'],
      ['Jeden Tag', 'übe', 'ich', 'zehn Minuten.'],
      ['Zuerst', 'machen', 'wir', 'die Hausaufgaben.'],
      ['Hoffentlich', 'scheint', 'morgen', 'die Sonne.'],
      ['Bei Regen', 'bleiben', 'wir', 'zu Hause.'],
      ['Für die Prüfung', 'lernt', 'sie', 'jeden Abend.'],
    ],
  },
  {
    id: 3,
    titel: 'Modalverben',
    ko: '조동사 괄호',
    tipp: '조동사(kann, muss, will…)는 두 번째 자리, 본동사 원형은 맨 끝! 괄호처럼 감싸요.',
    saetze: [
      ['Ich', 'kann', 'heute', 'nicht', 'kommen.'],
      ['Wir', 'müssen', 'jetzt', 'gehen.'],
      ['Er', 'will', 'Deutsch', 'lernen.'],
      ['Kannst', 'du', 'mir', 'helfen?'],
      ['Sie', 'möchte', 'einen Kaffee', 'trinken.'],
      ['Ich', 'muss', 'morgen früh', 'aufstehen.'],
      ['Man', 'darf', 'hier', 'nicht', 'rauchen.'],
      ['Ich', 'möchte', 'ein Zimmer', 'reservieren.'],
      ['Du', 'sollst', 'mehr Wasser', 'trinken.'],
      ['Wir', 'können', 'uns', 'am Freitag', 'treffen.'],
      ['Ich', 'will', 'im Sommer', 'nach Korea', 'fliegen.'],
      ['Ihr', 'könnt', 'bei uns', 'übernachten.'],
      ['Ich', 'kann', 'gut', 'schwimmen.'],
      ['Muss', 'ich', 'einen Termin', 'machen?'],
      ['Sie', 'darf', 'heute', 'länger', 'schlafen.'],
      ['Wir', 'wollen', 'eine Party', 'machen.'],
      ['Ich', 'möchte', 'mit Karte', 'bezahlen.'],
      ['Er', 'kann', 'leider', 'nicht', 'mitkommen.'],
      ['Du', 'musst', 'den Text', 'noch einmal', 'lesen.'],
      ['Wir', 'möchten', 'die Rechnung', 'bezahlen.'],
      ['Ich', 'soll', 'den Chef', 'anrufen.'],
      ['Kann', 'ich', 'das Fenster', 'öffnen?'],
      ['Sie', 'müssen', 'hier', 'kurz', 'warten.'],
      ['Ich', 'darf', 'kein Eis', 'essen.'],
      ['Wir', 'wollen', 'am Samstag', 'wandern.'],
    ],
  },
  {
    id: 4,
    titel: 'Perfekt',
    ko: '과거 괄호 (Perfekt)',
    tipp: 'haben/sein은 두 번째 자리, Partizip(ge-…)은 맨 끝! 또 괄호예요.',
    saetze: [
      ['Ich', 'habe', 'gestern', 'Pizza', 'gegessen.'],
      ['Wir', 'sind', 'nach Busan', 'gefahren.'],
      ['Sie', 'hat', 'ein Buch', 'gelesen.'],
      ['Er', 'ist', 'heute', 'spät', 'aufgestanden.'],
      ['Ich', 'habe', 'meine Oma', 'besucht.'],
      ['Hast', 'du', 'gut', 'geschlafen?'],
      ['Wir', 'haben', 'einen Film', 'gesehen.'],
      ['Ich', 'bin', 'zu Hause', 'geblieben.'],
      ['Sie', 'haben', 'viel', 'gelacht.'],
      ['Ich', 'habe', 'die Hausaufgaben', 'gemacht.'],
      ['Der Zug', 'ist', 'pünktlich', 'angekommen.'],
      ['Wir', 'haben', 'im Restaurant', 'gegessen.'],
      ['Ich', 'habe', 'ein Geschenk', 'gekauft.'],
      ['Bist', 'du', 'schon einmal', 'geflogen?'],
      ['Er', 'hat', 'den Bus', 'verpasst.'],
      ['Ich', 'habe', 'heute', 'Deutsch', 'geübt.'],
      ['Wir', 'sind', 'im Park', 'spazieren gegangen.'],
      ['Sie', 'ist', 'früh', 'eingeschlafen.'],
      ['Ich', 'habe', 'dir', 'eine Nachricht', 'geschrieben.'],
      ['Was', 'hast', 'du', 'am Wochenende', 'gemacht?'],
      ['Wir', 'haben', 'das Hotel', 'schnell', 'gefunden.'],
      ['Ich', 'bin', 'mit dem Rad', 'gefahren.'],
      ['Er', 'hat', 'mir', 'sehr', 'geholfen.'],
      ['Ich', 'habe', 'den Schlüssel', 'verloren.'],
      ['Sie', 'hat', 'einen Kuchen', 'gebacken.'],
    ],
  },
  {
    id: 5,
    titel: 'weil & dass',
    ko: '종속절 (동사 끝으로!)',
    tipp: 'weil/dass 뒤에는 동사가 문장 맨 끝으로 가요 — 드디어 한국어처럼!',
    saetze: [
      ['Ich bleibe zu Hause,', 'weil', 'ich', 'krank', 'bin.'],
      ['Ich denke,', 'dass', 'Deutsch', 'schwer', 'ist.'],
      ['Sie freut sich,', 'weil', 'morgen', 'ihr Geburtstag', 'ist.'],
      ['Ich hoffe,', 'dass', 'du', 'kommen', 'kannst.'],
      ['Wir nehmen ein Taxi,', 'weil', 'es', 'regnet.'],
      ['Er sagt,', 'dass', 'er', 'keine Zeit', 'hat.'],
      ['Ich lerne jeden Tag,', 'weil', 'die Prüfung', 'bald', 'ist.'],
      ['Ich glaube,', 'dass', 'das Restaurant', 'heute', 'geschlossen', 'ist.'],
      ['Sie ist müde,', 'weil', 'sie', 'früh', 'aufgestanden', 'ist.'],
      ['Ich weiß,', 'dass', 'du', 'gut', 'kochst.'],
      ['Wir bleiben drinnen,', 'weil', 'es', 'kalt', 'ist.'],
      ['Er schreibt,', 'dass', 'der Zug', 'Verspätung', 'hat.'],
      ['Ich bin glücklich,', 'weil', 'du', 'da', 'bist.'],
      ['Sie sagt,', 'dass', 'sie', 'morgen', 'anruft.'],
      ['Ich esse kein Fleisch,', 'weil', 'ich', 'Vegetarierin', 'bin.'],
      ['Ich finde,', 'dass', 'die Stadt', 'schön', 'ist.'],
      ['Er kommt später,', 'weil', 'er', 'noch', 'arbeiten', 'muss.'],
      ['Ich hoffe,', 'dass', 'das Wetter', 'gut', 'bleibt.'],
      ['Wir feiern heute,', 'weil', 'wir', 'die Prüfung', 'bestanden', 'haben.'],
      ['Sie glaubt,', 'dass', 'der Test', 'leicht', 'war.'],
      ['Ich rufe an,', 'weil', 'ich', 'eine Frage', 'habe.'],
      ['Er meint,', 'dass', 'wir', 'früher', 'kommen', 'sollen.'],
      ['Ich spare Geld,', 'weil', 'ich', 'reisen', 'möchte.'],
      ['Sie lernt viel,', 'weil', 'sie', 'in Deutschland', 'studieren', 'will.'],
      ['Ich denke,', 'dass', 'wir', 'ein Taxi', 'brauchen.'],
    ],
  },
]
