/* ============================================================
   SCHREIB-AUFGABEN — kuratierte Bank für Schreiben Teil 1 + 2
   (A2-Sprint Phase 1; Format und Wortlaut nach dem offiziellen
   Übungssatz: Situation, 3 Leitpunkte, Wortvorgabe)

   teil 1: SMS an eine vertraute Person (du), 20–30 Wörter
   teil 2: halb offizielle E-Mail (Sie), 30–40 Wörter

   hilfen = Satzanfänge für Stufe 1 („mit Geländer") — je einer
   pro Leitpunkt, antippbar ins Schreibfeld einfügbar.
   ko-Felder = die kleinen koreanischen Zeilen (Sprachregel).
   ============================================================ */

export const SCHREIB_AUFGABEN = [
  /* ---------- Teil 1: SMS (du, 20–30 Wörter) ---------- */
  {
    id: 't1-umzug',
    teil: 1,
    situation: 'Sie sind letzte Woche umgezogen und wohnen jetzt in einer neuen Wohnung. Schreiben Sie Ihrer Freundin Mia eine SMS.',
    situationKo: '지난주에 이사해서 새 집에 살아요. 친구 Mia에게 SMS를 쓰세요.',
    leitpunkte: [
      'Informieren Sie sie, wo Sie jetzt wohnen.',
      'Schreiben Sie, was Ihnen dort gefällt.',
      'Laden Sie Ihre Freundin in die neue Wohnung ein.',
    ],
    leitpunkteKo: ['지금 어디에 사는지 알리기', '거기서 뭐가 마음에 드는지 쓰기', '친구를 새 집에 초대하기'],
    anrede: 'Hallo Mia,',
    gruss: 'Bis bald,',
    hilfen: ['Ich wohne jetzt in …', 'Mir gefällt …, weil …', 'Möchtest du am … vorbeikommen?'],
  },
  {
    id: 't1-kino',
    teil: 1,
    situation: 'Sie möchten am Samstag mit Ihrem Freund Jonas ins Kino gehen. Schreiben Sie ihm eine SMS.',
    situationKo: '토요일에 친구 Jonas와 영화관에 가고 싶어요. SMS를 쓰세요.',
    leitpunkte: [
      'Laden Sie ihn ins Kino ein.',
      'Schreiben Sie, wann der Film beginnt.',
      'Fragen Sie, wo Sie sich treffen wollen.',
    ],
    leitpunkteKo: ['영화관에 초대하기', '영화가 언제 시작하는지 쓰기', '어디서 만날지 묻기'],
    anrede: 'Hallo Jonas,',
    gruss: 'Bis Samstag,',
    hilfen: ['Hast du Lust, am Samstag …?', 'Der Film beginnt um …', 'Wo wollen wir uns treffen?'],
  },
  {
    id: 't1-krank',
    teil: 1,
    situation: 'Sie sind krank und können heute nicht zum Deutschkurs kommen. Schreiben Sie Ihrer Freundin Lena aus dem Kurs eine SMS.',
    situationKo: '아파서 오늘 독일어 수업에 갈 수 없어요. 수업 친구 Lena에게 SMS를 쓰세요.',
    leitpunkte: [
      'Schreiben Sie, warum Sie nicht kommen.',
      'Bitten Sie sie um die Hausaufgaben.',
      'Schreiben Sie, wann Sie wiederkommen.',
    ],
    leitpunkteKo: ['왜 못 가는지 쓰기', '숙제를 부탁하기', '언제 다시 오는지 쓰기'],
    anrede: 'Liebe Lena,',
    gruss: 'Danke dir,',
    hilfen: ['Ich bin leider krank und …', 'Kannst du mir die Hausaufgaben schicken?', 'Ich komme am … wieder.'],
  },
  {
    id: 't1-geburtstag',
    teil: 1,
    situation: 'Sie machen am Freitag eine Geburtstagsparty. Schreiben Sie Ihrem Freund Tim eine SMS.',
    situationKo: '금요일에 생일 파티를 해요. 친구 Tim에게 SMS를 쓰세요.',
    leitpunkte: [
      'Laden Sie ihn zur Party ein.',
      'Schreiben Sie, wann die Party beginnt.',
      'Bitten Sie ihn, etwas zu trinken mitzubringen.',
    ],
    leitpunkteKo: ['파티에 초대하기', '파티가 언제 시작하는지 쓰기', '마실 것을 가져오라고 부탁하기'],
    anrede: 'Hallo Tim,',
    gruss: 'Bis Freitag,',
    hilfen: ['Am Freitag feiere ich …', 'Die Party beginnt um …', 'Kannst du bitte … mitbringen?'],
  },
  {
    id: 't1-verspaetung',
    teil: 1,
    situation: 'Sie sind mit Ihrer Freundin Anna um 18 Uhr verabredet. Ihr Zug hat Verspätung. Schreiben Sie ihr eine SMS.',
    situationKo: '친구 Anna와 18시에 만나기로 했는데 기차가 연착됐어요. SMS를 쓰세요.',
    leitpunkte: [
      'Erklären Sie, warum Sie zu spät kommen.',
      'Schreiben Sie, wann Sie ankommen.',
      'Machen Sie einen Vorschlag, wo Anna warten kann.',
    ],
    leitpunkteKo: ['왜 늦는지 설명하기', '언제 도착하는지 쓰기', 'Anna가 어디서 기다릴지 제안하기'],
    anrede: 'Liebe Anna,',
    gruss: 'Bis gleich,',
    hilfen: ['Mein Zug hat leider …', 'Ich komme erst um … an.', 'Warte doch im Café …'],
  },
  {
    id: 't1-hilfe-umzug',
    teil: 1,
    situation: 'Sie ziehen am Samstag um und brauchen Hilfe. Schreiben Sie Ihrem Freund Paul eine SMS.',
    situationKo: '토요일에 이사하는데 도움이 필요해요. 친구 Paul에게 SMS를 쓰세요.',
    leitpunkte: [
      'Bitten Sie ihn um Hilfe beim Umzug.',
      'Schreiben Sie, wann der Umzug beginnt.',
      'Schreiben Sie, was Sie danach zusammen machen können.',
    ],
    leitpunkteKo: ['이사를 도와달라고 부탁하기', '이사가 언제 시작하는지 쓰기', '끝나고 같이 뭘 할지 쓰기'],
    anrede: 'Hallo Paul,',
    gruss: 'Danke dir!',
    hilfen: ['Kannst du mir am Samstag …?', 'Wir fangen um … an.', 'Danach können wir zusammen …'],
  },
  {
    id: 't1-fundsache',
    teil: 1,
    situation: 'Ihre Freundin Sara war gestern bei Ihnen zu Besuch. Sie hat ihre Jacke vergessen. Schreiben Sie ihr eine SMS.',
    situationKo: '친구 Sara가 어제 놀러 왔다가 재킷을 두고 갔어요. SMS를 쓰세요.',
    leitpunkte: [
      'Informieren Sie sie, dass die Jacke bei Ihnen ist.',
      'Machen Sie einen Vorschlag, wie sie die Jacke bekommt.',
      'Fragen Sie, wann sie Zeit hat.',
    ],
    leitpunkteKo: ['재킷이 여기 있다고 알리기', '어떻게 돌려받을지 제안하기', '언제 시간이 있는지 묻기'],
    anrede: 'Hallo Sara,',
    gruss: 'Liebe Grüße,',
    hilfen: ['Deine Jacke ist noch …', 'Ich kann sie dir … bringen.', 'Wann hast du Zeit?'],
  },
  {
    id: 't1-restaurant',
    teil: 1,
    situation: 'Sie haben ein neues koreanisches Restaurant gefunden. Schreiben Sie Ihrer Freundin Julia eine SMS.',
    situationKo: '새로 생긴 한국 식당을 발견했어요. 친구 Julia에게 SMS를 쓰세요.',
    leitpunkte: [
      'Erzählen Sie von dem Restaurant.',
      'Schreiben Sie, was dort besonders gut ist.',
      'Schlagen Sie einen Termin zum Essen vor.',
    ],
    leitpunkteKo: ['식당에 대해 이야기하기', '뭐가 특히 맛있는지 쓰기', '같이 갈 날짜 제안하기'],
    anrede: 'Liebe Julia,',
    gruss: 'Bis bald,',
    hilfen: ['Ich habe ein tolles Restaurant …', 'Besonders gut ist …', 'Wollen wir am … hingehen?'],
  },
  {
    id: 't1-sport',
    teil: 1,
    situation: 'Sie machen jetzt jeden Mittwoch einen Yogakurs. Schreiben Sie Ihrer Freundin Emma eine SMS.',
    situationKo: '이제 매주 수요일에 요가 수업을 들어요. 친구 Emma에게 SMS를 쓰세요.',
    leitpunkte: [
      'Erzählen Sie vom Kurs.',
      'Schreiben Sie, warum der Kurs Ihnen gefällt.',
      'Fragen Sie, ob Emma mitkommen möchte.',
    ],
    leitpunkteKo: ['수업에 대해 이야기하기', '왜 마음에 드는지 쓰기', 'Emma도 같이 갈지 묻기'],
    anrede: 'Hallo Emma,',
    gruss: 'Liebe Grüße,',
    hilfen: ['Ich mache jetzt jeden Mittwoch …', 'Der Kurs gefällt mir, weil …', 'Möchtest du mitkommen?'],
  },
  {
    id: 't1-wochenende',
    teil: 1,
    situation: 'Sie planen einen Ausflug am Sonntag. Schreiben Sie Ihrem Freund Max eine SMS.',
    situationKo: '일요일에 소풍을 계획하고 있어요. 친구 Max에게 SMS를 쓰세요.',
    leitpunkte: [
      'Laden Sie ihn zum Ausflug ein.',
      'Schreiben Sie, wohin Sie fahren möchten.',
      'Schreiben Sie, was er mitbringen soll.',
    ],
    leitpunkteKo: ['소풍에 초대하기', '어디로 가고 싶은지 쓰기', '뭘 가져와야 하는지 쓰기'],
    anrede: 'Hallo Max,',
    gruss: 'Bis Sonntag,',
    hilfen: ['Hast du am Sonntag Zeit? Wir …', 'Ich möchte gern nach … fahren.', 'Bring bitte … mit.'],
  },
  {
    id: 't1-neue-arbeit',
    teil: 1,
    situation: 'Sie haben eine neue Arbeit gefunden. Schreiben Sie Ihrem Freund Leo eine SMS.',
    situationKo: '새 일자리를 구했어요. 친구 Leo에게 SMS를 쓰세요.',
    leitpunkte: [
      'Erzählen Sie von der neuen Arbeit.',
      'Schreiben Sie, wann Sie anfangen.',
      'Schlagen Sie vor, das zusammen zu feiern.',
    ],
    leitpunkteKo: ['새 일에 대해 이야기하기', '언제 시작하는지 쓰기', '같이 축하하자고 제안하기'],
    anrede: 'Hallo Leo,',
    gruss: 'Liebe Grüße,',
    hilfen: ['Ich habe eine neue Arbeit als …', 'Ich fange am … an.', 'Wollen wir das zusammen feiern?'],
  },
  {
    id: 't1-fahrrad',
    teil: 1,
    situation: 'Ihr Fahrrad ist kaputt. Ihr Freund Ben kann Fahrräder reparieren. Schreiben Sie ihm eine SMS.',
    situationKo: '자전거가 고장 났어요. 친구 Ben은 자전거를 고칠 줄 알아요. SMS를 쓰세요.',
    leitpunkte: [
      'Schreiben Sie, was kaputt ist.',
      'Bitten Sie ihn um Hilfe.',
      'Fragen Sie, wann er Zeit hat.',
    ],
    leitpunkteKo: ['뭐가 고장 났는지 쓰기', '도움을 부탁하기', '언제 시간이 있는지 묻기'],
    anrede: 'Hallo Ben,',
    gruss: 'Danke dir,',
    hilfen: ['Mein Fahrrad ist kaputt — …', 'Kannst du mir helfen?', 'Wann hast du Zeit?'],
  },

  /* ---------- Teil 2: E-Mail (Sie, 30–40 Wörter) ---------- */
  {
    id: 't2-hotel',
    teil: 2,
    situation: 'Sie haben ein Hotelzimmer gebucht. Sie wollten am Freitag anreisen. Leider können Sie erst am Sonntag kommen. Schreiben Sie eine E-Mail an Frau Yilmaz vom Hotel.',
    situationKo: '호텔을 예약했는데 금요일이 아니라 일요일에야 갈 수 있어요. 호텔의 Yilmaz 씨에게 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie, warum Sie schreiben.',
      'Informieren Sie sie, wie lange Sie jetzt bleiben möchten.',
      'Fragen Sie nach einem neuen Preisangebot.',
    ],
    leitpunkteKo: ['왜 쓰는지 설명하기', '이제 얼마나 머무는지 알리기', '새 가격 문의하기'],
    anrede: 'Sehr geehrte Frau Yilmaz,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['ich habe ein Zimmer gebucht, aber …', 'Ich möchte jetzt von … bis … bleiben.', 'Können Sie mir ein neues Angebot machen?'],
  },
  {
    id: 't2-kurs',
    teil: 2,
    situation: 'Sie möchten einen Deutschkurs an der Sprachschule Lingua besuchen. Schreiben Sie eine E-Mail an Herrn Weber von der Schule.',
    situationKo: 'Lingua 어학원에서 독일어 수업을 듣고 싶어요. 학원의 Weber 씨에게 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie, warum Sie schreiben.',
      'Fragen Sie nach den Kurszeiten.',
      'Fragen Sie, was der Kurs kostet.',
    ],
    leitpunkteKo: ['왜 쓰는지 설명하기', '수업 시간 묻기', '수업료 묻기'],
    anrede: 'Sehr geehrter Herr Weber,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['ich möchte gern einen Deutschkurs …', 'Wann finden die Kurse statt?', 'Was kostet der Kurs?'],
  },
  {
    id: 't2-termin',
    teil: 2,
    situation: 'Sie haben am Montag einen Termin bei Ihrer Zahnärztin Dr. Roth. Sie können nicht kommen. Schreiben Sie eine E-Mail an die Praxis.',
    situationKo: '월요일에 치과 예약이 있는데 갈 수 없어요. 병원에 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie, warum Sie absagen müssen.',
      'Entschuldigen Sie sich.',
      'Bitten Sie um einen neuen Termin.',
    ],
    leitpunkteKo: ['왜 취소해야 하는지 설명하기', '사과하기', '새 예약을 부탁하기'],
    anrede: 'Sehr geehrte Frau Dr. Roth,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['leider kann ich am Montag nicht …', 'Es tut mir sehr leid.', 'Können Sie mir einen neuen Termin geben?'],
  },
  {
    id: 't2-wohnung',
    teil: 2,
    situation: 'Sie haben im Internet eine Anzeige für eine Wohnung gesehen. Schreiben Sie eine E-Mail an den Vermieter, Herrn Schmidt.',
    situationKo: '인터넷에서 집 광고를 봤어요. 집주인 Schmidt 씨에게 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie, warum Sie schreiben.',
      'Stellen Sie zwei Fragen zur Wohnung.',
      'Bitten Sie um einen Besichtigungstermin.',
    ],
    leitpunkteKo: ['왜 쓰는지 설명하기', '집에 대해 두 가지 묻기', '집 보러 갈 약속을 부탁하기'],
    anrede: 'Sehr geehrter Herr Schmidt,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['ich habe Ihre Anzeige gesehen und …', 'Wie hoch ist die Miete? Gibt es …?', 'Kann ich die Wohnung besichtigen?'],
  },
  {
    id: 't2-bestellung',
    teil: 2,
    situation: 'Sie haben online einen Tisch bestellt. Der Tisch ist kaputt angekommen. Schreiben Sie eine E-Mail an den Kundenservice der Firma Möbel-Meyer.',
    situationKo: '온라인으로 주문한 탁자가 파손된 채 도착했어요. Möbel-Meyer 고객센터에 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie das Problem.',
      'Schreiben Sie, wann der Tisch angekommen ist.',
      'Fragen Sie, was Sie jetzt machen sollen.',
    ],
    leitpunkteKo: ['문제를 설명하기', '탁자가 언제 도착했는지 쓰기', '이제 어떻게 해야 하는지 묻기'],
    anrede: 'Sehr geehrte Damen und Herren,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['der Tisch aus meiner Bestellung ist leider …', 'Er ist am … angekommen.', 'Was soll ich jetzt machen?'],
  },
  {
    id: 't2-arbeit-krank',
    teil: 2,
    situation: 'Sie sind krank und können diese Woche nicht zur Arbeit kommen. Schreiben Sie eine E-Mail an Ihre Chefin, Frau Berger.',
    situationKo: '아파서 이번 주에 출근할 수 없어요. 상사 Berger 씨에게 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie, warum Sie nicht kommen können.',
      'Schreiben Sie, wie lange Sie krank sind.',
      'Informieren Sie sie über das Attest vom Arzt.',
    ],
    leitpunkteKo: ['왜 못 가는지 설명하기', '얼마나 아픈지(기간) 쓰기', '진단서에 대해 알리기'],
    anrede: 'Sehr geehrte Frau Berger,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['leider bin ich krank und …', 'Der Arzt sagt, ich muss bis … zu Hause bleiben.', 'Das Attest schicke ich Ihnen …'],
  },
  {
    id: 't2-fundbuero',
    teil: 2,
    situation: 'Sie haben im Zug nach Berlin Ihre Tasche vergessen. Schreiben Sie eine E-Mail an das Fundbüro der Bahn.',
    situationKo: '베를린행 기차에 가방을 두고 내렸어요. 철도 분실물 센터에 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie, warum Sie schreiben.',
      'Beschreiben Sie die Tasche.',
      'Fragen Sie, wie Sie die Tasche zurückbekommen können.',
    ],
    leitpunkteKo: ['왜 쓰는지 설명하기', '가방을 묘사하기', '어떻게 돌려받을 수 있는지 묻기'],
    anrede: 'Sehr geehrte Damen und Herren,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['ich habe im Zug nach Berlin …', 'Die Tasche ist … und …', 'Wie kann ich die Tasche zurückbekommen?'],
  },
  {
    id: 't2-einladung-firma',
    teil: 2,
    situation: 'Ihre Nachbarin, Frau Klein, hat Sie zum Sommerfest eingeladen. Sie können nicht kommen. Schreiben Sie ihr eine E-Mail.',
    situationKo: '이웃 Klein 씨가 여름 파티에 초대했는데 갈 수 없어요. 이메일을 쓰세요.',
    leitpunkte: [
      'Bedanken Sie sich für die Einladung.',
      'Erklären Sie, warum Sie nicht kommen können.',
      'Schlagen Sie ein anderes Treffen vor.',
    ],
    leitpunkteKo: ['초대에 감사하기', '왜 못 가는지 설명하기', '다른 만남을 제안하기'],
    anrede: 'Sehr geehrte Frau Klein,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['vielen Dank für die Einladung …', 'Leider kann ich nicht kommen, weil …', 'Vielleicht können wir …'],
  },
  {
    id: 't2-bibliothek',
    teil: 2,
    situation: 'Sie haben ein Buch aus der Stadtbibliothek verloren. Schreiben Sie eine E-Mail an die Bibliothek.',
    situationKo: '시립 도서관에서 빌린 책을 잃어버렸어요. 도서관에 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie das Problem.',
      'Entschuldigen Sie sich.',
      'Fragen Sie, was das Buch kostet.',
    ],
    leitpunkteKo: ['문제를 설명하기', '사과하기', '책값이 얼마인지 묻기'],
    anrede: 'Sehr geehrte Damen und Herren,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['ich habe leider ein Buch …', 'Das tut mir sehr leid.', 'Was kostet das Buch?'],
  },
  {
    id: 't2-praktikum',
    teil: 2,
    situation: 'Sie möchten ein Praktikum im Café Sonne machen. Schreiben Sie eine E-Mail an die Chefin, Frau Wagner.',
    situationKo: 'Café Sonne에서 실습을 하고 싶어요. 사장 Wagner 씨에게 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie, warum Sie schreiben.',
      'Schreiben Sie etwas über sich.',
      'Fragen Sie, wann Sie anfangen können.',
    ],
    leitpunkteKo: ['왜 쓰는지 설명하기', '자기소개 한두 문장 쓰기', '언제 시작할 수 있는지 묻기'],
    anrede: 'Sehr geehrte Frau Wagner,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['ich möchte gern ein Praktikum …', 'Ich komme aus Korea und …', 'Wann kann ich anfangen?'],
  },
  {
    id: 't2-nachbar-laerm',
    teil: 2,
    situation: 'Ihr Nachbar, Herr Braun, macht jeden Abend laute Musik. Sie können nicht schlafen. Schreiben Sie ihm eine E-Mail.',
    situationKo: '이웃 Braun 씨가 매일 저녁 시끄럽게 음악을 틀어서 잠을 잘 수 없어요. 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie das Problem.',
      'Schreiben Sie, warum Sie das stört.',
      'Machen Sie einen Vorschlag.',
    ],
    leitpunkteKo: ['문제를 설명하기', '왜 불편한지 쓰기', '해결책을 제안하기'],
    anrede: 'Sehr geehrter Herr Braun,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['jeden Abend höre ich laute Musik …', 'Ich kann leider nicht schlafen, weil …', 'Können Sie bitte ab 22 Uhr …?'],
  },
  {
    id: 't2-volkshochschule',
    teil: 2,
    situation: 'Sie haben einen Kochkurs an der Volkshochschule gebucht, aber Sie können am ersten Termin nicht kommen. Schreiben Sie eine E-Mail an Herrn Fischer von der Volkshochschule.',
    situationKo: '시민학교 요리 수업을 신청했는데 첫 수업에 갈 수 없어요. 담당자 Fischer 씨에게 이메일을 쓰세요.',
    leitpunkte: [
      'Erklären Sie, warum Sie schreiben.',
      'Entschuldigen Sie sich für den ersten Termin.',
      'Fragen Sie, was Sie für den zweiten Termin mitbringen sollen.',
    ],
    leitpunkteKo: ['왜 쓰는지 설명하기', '첫 수업 불참을 사과하기', '두 번째 수업에 뭘 가져가야 하는지 묻기'],
    anrede: 'Sehr geehrter Herr Fischer,',
    gruss: 'Mit freundlichen Grüßen',
    hilfen: ['ich habe den Kochkurs gebucht, aber …', 'Es tut mir leid, dass …', 'Was soll ich zum zweiten Termin mitbringen?'],
  },
]

/* Wortvorgaben je Teil (aus dem Übungssatz) */
export const WORTBAND = {
  1: { min: 20, max: 30 },
  2: { min: 30, max: 40 },
}
