/* ============================================================
   NACHZIEHSTAPEL — DEUTSCH (für 해인)

   Sortiert nach HÄUFIGKEIT, häufigstes zuerst. Grundlage ist mein
   Wissen über deutsche Häufigkeitslisten (Leipziger Wortschatz
   u. ä.). Die Größenordnung stimmt — die exakte Rangfolge Platz
   für Platz ist eine Näherung.

   Felder (Namen wie in der Datenbank, "ko" ist immer die
   ZIELsprache, "en" immer die Bedeutung):
     ko    deutsches Wort — Substantive MIT Artikel
     en    'English (한국어)' — ihr gewünschtes Format
     pos   Wortart, füllt beim Nachziehen die neue Spalte
     ex    kurzer Beispielsatz
     exEn  Übersetzung des Beispiels

   WICHTIG für die Duplikat-Sperre: die Schreibweise muss exakt
   der in ihrer Bibliothek entsprechen (Artikel klein, Substantiv
   groß, Verben im Infinitiv). Sonst rutscht ein Wort doppelt rein.

   Bewusst NICHT drin: Wörter, die sich als Karteikarte schlecht
   abfragen lassen — Modalpartikeln (doch, ja, mal, eben, halt),
   reine Präpositionen und Artikel. Die lernt man im Satz, nicht
   einzeln.
   ============================================================ */
export const germanPool = [
  // ---------- Die absoluten Kernverben ----------
  { ko: 'sein', en: 'to be (이다, 있다)', pos: 'verb', ex: 'Ich bin müde.', exEn: '저는 피곤해요.' },
  { ko: 'haben', en: 'to have (가지다)', pos: 'verb', ex: 'Ich habe Zeit.', exEn: '저는 시간이 있어요.' },
  { ko: 'werden', en: 'to become (되다)', pos: 'verb', ex: 'Es wird kalt.', exEn: '추워지고 있어요.' },
  { ko: 'können', en: 'can, to be able to (할 수 있다)', pos: 'verb', ex: 'Ich kann schwimmen.', exEn: '저는 수영할 수 있어요.' },
  { ko: 'müssen', en: 'must, to have to (해야 하다)', pos: 'verb', ex: 'Ich muss gehen.', exEn: '저는 가야 해요.' },
  { ko: 'wollen', en: 'to want (원하다)', pos: 'verb', ex: 'Ich will schlafen.', exEn: '저는 자고 싶어요.' },
  { ko: 'sollen', en: 'should (해야 한다)', pos: 'verb', ex: 'Du sollst warten.', exEn: '기다려야 해요.' },
  { ko: 'dürfen', en: 'may, to be allowed (해도 되다)', pos: 'verb', ex: 'Darf ich fragen?', exEn: '물어봐도 될까요?' },
  { ko: 'lassen', en: 'to let, to leave (놓다, 하게 하다)', pos: 'verb', ex: 'Lass mich helfen.', exEn: '제가 도울게요.' },
  { ko: 'stehen', en: 'to stand (서 있다)', pos: 'verb', ex: 'Er steht dort.', exEn: '그는 저기 서 있어요.' },
  { ko: 'finden', en: 'to find (찾다)', pos: 'verb', ex: 'Ich finde es gut.', exEn: '저는 좋다고 생각해요.' },
  { ko: 'bleiben', en: 'to stay (머무르다)', pos: 'verb', ex: 'Bleib bitte hier.', exEn: '여기 있어 주세요.' },
  { ko: 'liegen', en: 'to lie, to be located (놓여 있다)', pos: 'verb', ex: 'Das Buch liegt da.', exEn: '책이 저기 있어요.' },
  { ko: 'tun', en: 'to do (하다)', pos: 'verb', ex: 'Was tust du?', exEn: '뭐 해요?' },
  { ko: 'glauben', en: 'to believe (믿다)', pos: 'verb', ex: 'Ich glaube dir.', exEn: '저는 당신을 믿어요.' },
  { ko: 'halten', en: 'to hold (잡다)', pos: 'verb', ex: 'Halt das bitte.', exEn: '이것 좀 들어 주세요.' },
  { ko: 'zeigen', en: 'to show (보여 주다)', pos: 'verb', ex: 'Zeig mir das Bild.', exEn: '사진 좀 보여 주세요.' },
  { ko: 'bringen', en: 'to bring (가져오다)', pos: 'verb', ex: 'Bring mir Wasser.', exEn: '물 좀 가져다주세요.' },
  { ko: 'leben', en: 'to live (살다)', pos: 'verb', ex: 'Sie lebt in Berlin.', exEn: '그녀는 베를린에 살아요.' },
  { ko: 'meinen', en: 'to mean, to think (생각하다)', pos: 'verb', ex: 'Was meinst du?', exEn: '어떻게 생각해요?' },
  { ko: 'fragen', en: 'to ask (묻다)', pos: 'verb', ex: 'Darf ich etwas fragen?', exEn: '뭐 좀 물어봐도 돼요?' },
  { ko: 'kennen', en: 'to know a person (알다)', pos: 'verb', ex: 'Ich kenne ihn.', exEn: '저는 그를 알아요.' },
  { ko: 'stellen', en: 'to put, to place (놓다)', pos: 'verb', ex: 'Stell es auf den Tisch.', exEn: '탁자 위에 놓으세요.' },
  { ko: 'spielen', en: 'to play (놀다, 연주하다)', pos: 'verb', ex: 'Die Kinder spielen.', exEn: '아이들이 놀아요.' },
  { ko: 'verstehen', en: 'to understand (이해하다)', pos: 'verb', ex: 'Ich verstehe nicht.', exEn: '이해가 안 돼요.' },
  { ko: 'setzen', en: 'to set, to sit down (앉히다)', pos: 'verb', ex: 'Setz dich bitte.', exEn: '앉으세요.' },
  { ko: 'bekommen', en: 'to get, to receive (받다)', pos: 'verb', ex: 'Ich bekomme einen Brief.', exEn: '저는 편지를 받아요.' },
  { ko: 'beginnen', en: 'to begin (시작하다)', pos: 'verb', ex: 'Der Film beginnt.', exEn: '영화가 시작해요.' },
  { ko: 'erzählen', en: 'to tell (이야기하다)', pos: 'verb', ex: 'Erzähl mir mehr.', exEn: '더 얘기해 주세요.' },
  { ko: 'versuchen', en: 'to try (시도하다)', pos: 'verb', ex: 'Ich versuche es.', exEn: '한번 해 볼게요.' },
  { ko: 'laufen', en: 'to run, to walk (달리다, 걷다)', pos: 'verb', ex: 'Wir laufen nach Hause.', exEn: '우리는 걸어서 집에 가요.' },
  { ko: 'erklären', en: 'to explain (설명하다)', pos: 'verb', ex: 'Kannst du das erklären?', exEn: '설명해 줄 수 있어요?' },
  { ko: 'schließen', en: 'to close (닫다)', pos: 'verb', ex: 'Schließ bitte die Tür.', exEn: '문 좀 닫아 주세요.' },
  { ko: 'verlieren', en: 'to lose (잃다)', pos: 'verb', ex: 'Ich habe den Schlüssel verloren.', exEn: '열쇠를 잃어버렸어요.' },
  { ko: 'gewinnen', en: 'to win (이기다)', pos: 'verb', ex: 'Wir gewinnen das Spiel.', exEn: '우리가 경기를 이겨요.' },
  { ko: 'tragen', en: 'to carry, to wear (들다, 입다)', pos: 'verb', ex: 'Sie trägt einen Mantel.', exEn: '그녀는 코트를 입어요.' },
  { ko: 'ziehen', en: 'to pull (당기다)', pos: 'verb', ex: 'Zieh die Tür zu.', exEn: '문을 당겨 닫으세요.' },
  { ko: 'legen', en: 'to lay, to put down (눕히다, 놓다)', pos: 'verb', ex: 'Leg das Buch hin.', exEn: '책을 내려놓으세요.' },
  { ko: 'fallen', en: 'to fall (떨어지다)', pos: 'verb', ex: 'Der Schnee fällt.', exEn: '눈이 내려요.' },
  { ko: 'fühlen', en: 'to feel (느끼다)', pos: 'verb', ex: 'Ich fühle mich gut.', exEn: '기분이 좋아요.' },
  { ko: 'bezahlen', en: 'to pay (지불하다)', pos: 'verb', ex: 'Ich möchte bezahlen.', exEn: '계산할게요.' },
  { ko: 'vergessen', en: 'to forget (잊다)', pos: 'verb', ex: 'Ich habe es vergessen.', exEn: '잊어버렸어요.' },
  { ko: 'erinnern', en: 'to remember (기억하다)', pos: 'verb', ex: 'Ich erinnere mich daran.', exEn: '그걸 기억해요.' },
  { ko: 'anfangen', en: 'to start (시작하다)', pos: 'verb', ex: 'Wann fangen wir an?', exEn: '우리 언제 시작해요?' },
  { ko: 'aufhören', en: 'to stop (그만두다)', pos: 'verb', ex: 'Hör bitte auf.', exEn: '그만해 주세요.' },
  { ko: 'aufstehen', en: 'to get up (일어나다)', pos: 'verb', ex: 'Ich stehe früh auf.', exEn: '저는 일찍 일어나요.' },
  { ko: 'einkaufen', en: 'to go shopping (장을 보다)', pos: 'verb', ex: 'Wir kaufen heute ein.', exEn: '우리는 오늘 장을 봐요.' },
  { ko: 'anrufen', en: 'to call on the phone (전화하다)', pos: 'verb', ex: 'Ich rufe dich an.', exEn: '제가 전화할게요.' },
  { ko: 'mitkommen', en: 'to come along (같이 가다)', pos: 'verb', ex: 'Kommst du mit?', exEn: '같이 갈래요?' },
  { ko: 'schmecken', en: 'to taste (맛이 나다)', pos: 'verb', ex: 'Das schmeckt gut.', exEn: '맛있어요.' },

  // ---------- Die häufigsten Substantive ----------
  { ko: 'die Zeit', en: 'time (시간)', pos: 'noun', ex: 'Ich habe keine Zeit.', exEn: '저는 시간이 없어요.' },
  { ko: 'das Jahr', en: 'year (년, 해)', pos: 'noun', ex: 'Das Jahr ist vorbei.', exEn: '한 해가 지났어요.' },
  { ko: 'der Tag', en: 'day (날, 하루)', pos: 'noun', ex: 'Der Tag war schön.', exEn: '오늘 하루가 좋았어요.' },
  { ko: 'der Mensch', en: 'human, person (사람)', pos: 'noun', ex: 'Der Mensch braucht Schlaf.', exEn: '사람은 잠이 필요해요.' },
  { ko: 'die Frau', en: 'woman, wife (여자, 아내)', pos: 'noun', ex: 'Die Frau ist Ärztin.', exEn: '그 여자는 의사예요.' },
  { ko: 'der Mann', en: 'man, husband (남자, 남편)', pos: 'noun', ex: 'Der Mann liest.', exEn: '그 남자는 책을 읽어요.' },
  { ko: 'die Hand', en: 'hand (손)', pos: 'noun', ex: 'Gib mir die Hand.', exEn: '손 좀 주세요.' },
  { ko: 'das Land', en: 'country (나라)', pos: 'noun', ex: 'Das Land ist schön.', exEn: '그 나라는 아름다워요.' },
  { ko: 'die Welt', en: 'world (세계)', pos: 'noun', ex: 'Die Welt ist groß.', exEn: '세계는 넓어요.' },
  { ko: 'das Leben', en: 'life (삶, 인생)', pos: 'noun', ex: 'Das Leben ist kurz.', exEn: '인생은 짧아요.' },
  { ko: 'das Haus', en: 'house (집)', pos: 'noun', ex: 'Das Haus ist alt.', exEn: '그 집은 오래됐어요.' },
  { ko: 'die Stadt', en: 'city (도시)', pos: 'noun', ex: 'Die Stadt ist laut.', exEn: '도시는 시끄러워요.' },
  { ko: 'die Frage', en: 'question (질문)', pos: 'noun', ex: 'Ich habe eine Frage.', exEn: '질문이 있어요.' },
  { ko: 'die Arbeit', en: 'work (일)', pos: 'noun', ex: 'Die Arbeit ist fertig.', exEn: '일이 끝났어요.' },
  { ko: 'das Auge', en: 'eye (눈)', pos: 'noun', ex: 'Ihre Augen sind braun.', exEn: '그녀의 눈은 갈색이에요.' },
  { ko: 'die Nacht', en: 'night (밤)', pos: 'noun', ex: 'Gute Nacht!', exEn: '잘 자요!' },
  { ko: 'die Woche', en: 'week (주)', pos: 'noun', ex: 'Nächste Woche habe ich frei.', exEn: '다음 주에 쉬어요.' },
  { ko: 'der Monat', en: 'month (달)', pos: 'noun', ex: 'Der Monat ist fast vorbei.', exEn: '이번 달이 거의 끝났어요.' },
  { ko: 'die Stunde', en: 'hour (시간)', pos: 'noun', ex: 'Es dauert eine Stunde.', exEn: '한 시간 걸려요.' },
  { ko: 'die Minute', en: 'minute (분)', pos: 'noun', ex: 'Warte eine Minute.', exEn: '일 분만 기다려요.' },
  { ko: 'der Freund', en: 'friend, boyfriend (친구, 남자친구)', pos: 'noun', ex: 'Mein Freund kommt heute.', exEn: '제 친구가 오늘 와요.' },
  { ko: 'die Schule', en: 'school (학교)', pos: 'noun', ex: 'Die Schule beginnt um acht.', exEn: '학교는 여덟 시에 시작해요.' },
  { ko: 'das Buch', en: 'book (책)', pos: 'noun', ex: 'Ich lese ein Buch.', exEn: '저는 책을 읽어요.' },
  { ko: 'die Tür', en: 'door (문)', pos: 'noun', ex: 'Die Tür ist offen.', exEn: '문이 열려 있어요.' },
  { ko: 'das Fenster', en: 'window (창문)', pos: 'noun', ex: 'Mach das Fenster zu.', exEn: '창문을 닫으세요.' },
  { ko: 'der Tisch', en: 'table (탁자)', pos: 'noun', ex: 'Das Essen steht auf dem Tisch.', exEn: '음식이 탁자에 있어요.' },
  { ko: 'der Stuhl', en: 'chair (의자)', pos: 'noun', ex: 'Der Stuhl ist bequem.', exEn: '그 의자는 편해요.' },
  { ko: 'das Bett', en: 'bed (침대)', pos: 'noun', ex: 'Ich gehe ins Bett.', exEn: '저는 자러 가요.' },
  { ko: 'das Zimmer', en: 'room (방)', pos: 'noun', ex: 'Mein Zimmer ist klein.', exEn: '제 방은 작아요.' },
  { ko: 'die Wohnung', en: 'flat, apartment (집, 아파트)', pos: 'noun', ex: 'Die Wohnung ist hell.', exEn: '집이 밝아요.' },
  { ko: 'die Straße', en: 'street (길, 거리)', pos: 'noun', ex: 'Die Straße ist lang.', exEn: '그 길은 길어요.' },
  { ko: 'das Auto', en: 'car (자동차)', pos: 'noun', ex: 'Das Auto ist neu.', exEn: '그 차는 새 거예요.' },
  { ko: 'der Zug', en: 'train (기차)', pos: 'noun', ex: 'Der Zug kommt gleich.', exEn: '기차가 곧 와요.' },
  { ko: 'der Weg', en: 'way, path (길)', pos: 'noun', ex: 'Der Weg ist weit.', exEn: '길이 멀어요.' },
  { ko: 'das Essen', en: 'food, meal (음식, 식사)', pos: 'noun', ex: 'Das Essen ist fertig.', exEn: '음식이 다 됐어요.' },
  { ko: 'der Kaffee', en: 'coffee (커피)', pos: 'noun', ex: 'Ich trinke Kaffee.', exEn: '저는 커피를 마셔요.' },
  { ko: 'die Milch', en: 'milk (우유)', pos: 'noun', ex: 'Die Milch ist kalt.', exEn: '우유가 차가워요.' },
  { ko: 'das Brot', en: 'bread (빵)', pos: 'noun', ex: 'Das Brot ist frisch.', exEn: '빵이 신선해요.' },
  { ko: 'der Name', en: 'name (이름)', pos: 'noun', ex: 'Wie ist dein Name?', exEn: '이름이 뭐예요?' },
  { ko: 'das Wort', en: 'word (단어)', pos: 'noun', ex: 'Ich kenne das Wort nicht.', exEn: '그 단어를 몰라요.' },
  { ko: 'die Sprache', en: 'language (언어)', pos: 'noun', ex: 'Deutsch ist eine schwere Sprache.', exEn: '독일어는 어려운 언어예요.' },
  { ko: 'die Musik', en: 'music (음악)', pos: 'noun', ex: 'Ich höre gern Musik.', exEn: '저는 음악 듣는 걸 좋아해요.' },
  { ko: 'der Film', en: 'film, movie (영화)', pos: 'noun', ex: 'Der Film war gut.', exEn: '그 영화는 좋았어요.' },
  { ko: 'das Bild', en: 'picture (사진, 그림)', pos: 'noun', ex: 'Das Bild ist schön.', exEn: '그 사진은 예뻐요.' },
  { ko: 'das Wetter', en: 'weather (날씨)', pos: 'noun', ex: 'Das Wetter ist gut.', exEn: '날씨가 좋아요.' },
  { ko: 'die Sonne', en: 'sun (해)', pos: 'noun', ex: 'Die Sonne scheint.', exEn: '해가 나요.' },
  { ko: 'der Regen', en: 'rain (비)', pos: 'noun', ex: 'Der Regen hört auf.', exEn: '비가 그쳐요.' },
  { ko: 'der Schnee', en: 'snow (눈)', pos: 'noun', ex: 'Der Schnee ist weiß.', exEn: '눈이 하얘요.' },
  { ko: 'das Problem', en: 'problem (문제)', pos: 'noun', ex: 'Das ist kein Problem.', exEn: '그건 문제없어요.' },
  { ko: 'die Idee', en: 'idea (생각, 아이디어)', pos: 'noun', ex: 'Das ist eine gute Idee.', exEn: '좋은 생각이에요.' },
  { ko: 'der Grund', en: 'reason (이유)', pos: 'noun', ex: 'Es gibt einen Grund.', exEn: '이유가 있어요.' },
  { ko: 'die Sache', en: 'thing, matter (일, 것)', pos: 'noun', ex: 'Die Sache ist wichtig.', exEn: '그 일은 중요해요.' },
  { ko: 'das Ding', en: 'thing (물건)', pos: 'noun', ex: 'Was ist das für ein Ding?', exEn: '그게 무슨 물건이에요?' },
  { ko: 'das Beispiel', en: 'example (예)', pos: 'noun', ex: 'Gib mir ein Beispiel.', exEn: '예를 들어 주세요.' },
  { ko: 'die Person', en: 'person (사람)', pos: 'noun', ex: 'Die Person kenne ich nicht.', exEn: '그 사람을 몰라요.' },
  { ko: 'die Firma', en: 'company (회사)', pos: 'noun', ex: 'Die Firma ist groß.', exEn: '그 회사는 커요.' },
  { ko: 'das Büro', en: 'office (사무실)', pos: 'noun', ex: 'Ich arbeite im Büro.', exEn: '저는 사무실에서 일해요.' },
  { ko: 'der Lehrer', en: 'teacher (선생님)', pos: 'noun', ex: 'Der Lehrer erklärt es.', exEn: '선생님이 설명해요.' },
  { ko: 'der Arzt', en: 'doctor (의사)', pos: 'noun', ex: 'Ich gehe zum Arzt.', exEn: '저는 병원에 가요.' },
  { ko: 'der Bahnhof', en: 'train station (기차역)', pos: 'noun', ex: 'Wo ist der Bahnhof?', exEn: '기차역이 어디예요?' },
  { ko: 'das Hotel', en: 'hotel (호텔)', pos: 'noun', ex: 'Das Hotel ist teuer.', exEn: '그 호텔은 비싸요.' },
  { ko: 'das Restaurant', en: 'restaurant (식당)', pos: 'noun', ex: 'Das Restaurant ist voll.', exEn: '식당이 꽉 찼어요.' },
  { ko: 'der Markt', en: 'market (시장)', pos: 'noun', ex: 'Wir gehen auf den Markt.', exEn: '우리는 시장에 가요.' },
  { ko: 'die Bank', en: 'bank (은행)', pos: 'noun', ex: 'Die Bank ist geschlossen.', exEn: '은행이 문을 닫았어요.' },
  { ko: 'der Park', en: 'park (공원)', pos: 'noun', ex: 'Der Park ist schön.', exEn: '공원이 예뻐요.' },
  { ko: 'der Garten', en: 'garden (정원)', pos: 'noun', ex: 'Der Garten ist groß.', exEn: '정원이 커요.' },
  { ko: 'der Baum', en: 'tree (나무)', pos: 'noun', ex: 'Der Baum ist alt.', exEn: '그 나무는 오래됐어요.' },
  { ko: 'die Blume', en: 'flower (꽃)', pos: 'noun', ex: 'Die Blume ist rot.', exEn: '꽃이 빨개요.' },
  { ko: 'das Tier', en: 'animal (동물)', pos: 'noun', ex: 'Ich liebe Tiere.', exEn: '저는 동물을 좋아해요.' },

  // ---------- Die häufigsten Adjektive ----------
  { ko: 'gut', en: 'good (좋은)', pos: 'adj', ex: 'Das Wetter ist gut.', exEn: '날씨가 좋아요.' },
  { ko: 'groß', en: 'big, tall (큰)', pos: 'adj', ex: 'Der Hund ist groß.', exEn: '그 개는 커요.' },
  { ko: 'neu', en: 'new (새로운)', pos: 'adj', ex: 'Ich habe ein neues Handy.', exEn: '저는 새 휴대폰이 있어요.' },
  { ko: 'alt', en: 'old (오래된, 나이 든)', pos: 'adj', ex: 'Wie alt bist du?', exEn: '몇 살이에요?' },
  { ko: 'klein', en: 'small (작은)', pos: 'adj', ex: 'Die Wohnung ist klein.', exEn: '집이 작아요.' },
  { ko: 'lang', en: 'long (긴)', pos: 'adj', ex: 'Der Weg ist lang.', exEn: '길이 길어요.' },
  { ko: 'hoch', en: 'high (높은)', pos: 'adj', ex: 'Der Berg ist hoch.', exEn: '산이 높아요.' },
  { ko: 'jung', en: 'young (젊은)', pos: 'adj', ex: 'Sie ist noch jung.', exEn: '그녀는 아직 젊어요.' },
  { ko: 'wichtig', en: 'important (중요한)', pos: 'adj', ex: 'Das ist sehr wichtig.', exEn: '그건 아주 중요해요.' },
  { ko: 'richtig', en: 'correct (맞는)', pos: 'adj', ex: 'Die Antwort ist richtig.', exEn: '답이 맞아요.' },
  { ko: 'falsch', en: 'wrong (틀린)', pos: 'adj', ex: 'Das ist falsch.', exEn: '그건 틀렸어요.' },
  { ko: 'schön', en: 'beautiful, nice (아름다운)', pos: 'adj', ex: 'Der Tag war schön.', exEn: '오늘 하루가 좋았어요.' },
  { ko: 'schnell', en: 'fast (빠른)', pos: 'adj', ex: 'Der Zug ist schnell.', exEn: '기차가 빨라요.' },
  { ko: 'langsam', en: 'slow (느린)', pos: 'adj', ex: 'Bitte sprich langsam.', exEn: '천천히 말해 주세요.' },
  { ko: 'schwer', en: 'heavy, difficult (무거운, 어려운)', pos: 'adj', ex: 'Deutsch ist schwer.', exEn: '독일어는 어려워요.' },
  { ko: 'leicht', en: 'light, easy (가벼운, 쉬운)', pos: 'adj', ex: 'Die Tasche ist leicht.', exEn: '가방이 가벼워요.' },
  { ko: 'stark', en: 'strong (강한)', pos: 'adj', ex: 'Er ist sehr stark.', exEn: '그는 아주 힘이 세요.' },
  { ko: 'warm', en: 'warm (따뜻한)', pos: 'adj', ex: 'Das Wasser ist warm.', exEn: '물이 따뜻해요.' },
  { ko: 'kalt', en: 'cold (추운, 차가운)', pos: 'adj', ex: 'Heute ist es kalt.', exEn: '오늘은 추워요.' },
  { ko: 'heiß', en: 'hot (뜨거운)', pos: 'adj', ex: 'Der Kaffee ist heiß.', exEn: '커피가 뜨거워요.' },
  { ko: 'teuer', en: 'expensive (비싼)', pos: 'adj', ex: 'Das ist zu teuer.', exEn: '너무 비싸요.' },
  { ko: 'billig', en: 'cheap (싼)', pos: 'adj', ex: 'Das Brot ist billig.', exEn: '빵이 싸요.' },
  { ko: 'glücklich', en: 'happy (행복한)', pos: 'adj', ex: 'Ich bin glücklich.', exEn: '저는 행복해요.' },
  { ko: 'traurig', en: 'sad (슬픈)', pos: 'adj', ex: 'Warum bist du traurig?', exEn: '왜 슬퍼요?' },
  { ko: 'müde', en: 'tired (피곤한)', pos: 'adj', ex: 'Ich bin sehr müde.', exEn: '저는 아주 피곤해요.' },
  { ko: 'krank', en: 'ill, sick (아픈)', pos: 'adj', ex: 'Sie ist krank.', exEn: '그녀는 아파요.' },
  { ko: 'gesund', en: 'healthy (건강한)', pos: 'adj', ex: 'Obst ist gesund.', exEn: '과일은 건강에 좋아요.' },
  { ko: 'voll', en: 'full (가득 찬)', pos: 'adj', ex: 'Der Bus ist voll.', exEn: '버스가 꽉 찼어요.' },
  { ko: 'leer', en: 'empty (빈)', pos: 'adj', ex: 'Das Glas ist leer.', exEn: '컵이 비었어요.' },
  { ko: 'offen', en: 'open (열린)', pos: 'adj', ex: 'Der Laden ist offen.', exEn: '가게가 열려 있어요.' },
  { ko: 'früh', en: 'early (이른)', pos: 'adj', ex: 'Es ist noch früh.', exEn: '아직 일러요.' },
  { ko: 'spät', en: 'late (늦은)', pos: 'adj', ex: 'Es ist schon spät.', exEn: '벌써 늦었어요.' },
  { ko: 'sicher', en: 'sure, safe (확실한, 안전한)', pos: 'adj', ex: 'Bist du sicher?', exEn: '확실해요?' },
  { ko: 'möglich', en: 'possible (가능한)', pos: 'adj', ex: 'Das ist möglich.', exEn: '그건 가능해요.' },
  { ko: 'fertig', en: 'ready, finished (다 된)', pos: 'adj', ex: 'Ich bin fertig.', exEn: '저는 다 했어요.' },
  { ko: 'frei', en: 'free (자유로운, 비어 있는)', pos: 'adj', ex: 'Ist der Platz frei?', exEn: '이 자리 비었어요?' },
  { ko: 'laut', en: 'loud (시끄러운)', pos: 'adj', ex: 'Die Musik ist laut.', exEn: '음악이 시끄러워요.' },
  { ko: 'leise', en: 'quiet (조용한)', pos: 'adj', ex: 'Sprich bitte leise.', exEn: '조용히 말해 주세요.' },
  { ko: 'hell', en: 'bright (밝은)', pos: 'adj', ex: 'Das Zimmer ist hell.', exEn: '방이 밝아요.' },
  { ko: 'dunkel', en: 'dark (어두운)', pos: 'adj', ex: 'Draußen ist es dunkel.', exEn: '밖이 어두워요.' },
  { ko: 'lecker', en: 'delicious (맛있는)', pos: 'adj', ex: 'Das war lecker!', exEn: '맛있었어요!' },
  { ko: 'freundlich', en: 'friendly (친절한)', pos: 'adj', ex: 'Sie ist sehr freundlich.', exEn: '그녀는 아주 친절해요.' },
  { ko: 'nett', en: 'nice, kind (착한)', pos: 'adj', ex: 'Das ist nett von dir.', exEn: '고마워요.' },
  { ko: 'lustig', en: 'funny (재미있는)', pos: 'adj', ex: 'Der Film ist lustig.', exEn: '그 영화는 재미있어요.' },
  { ko: 'interessant', en: 'interesting (흥미로운)', pos: 'adj', ex: 'Das Buch ist interessant.', exEn: '그 책은 재미있어요.' },
  { ko: 'langweilig', en: 'boring (지루한)', pos: 'adj', ex: 'Mir ist langweilig.', exEn: '심심해요.' },
  { ko: 'sauber', en: 'clean (깨끗한)', pos: 'adj', ex: 'Das Zimmer ist sauber.', exEn: '방이 깨끗해요.' },
  { ko: 'ruhig', en: 'calm, quiet (조용한)', pos: 'adj', ex: 'Bleib ruhig.', exEn: '진정하세요.' },
  { ko: 'weit', en: 'far (먼)', pos: 'adj', ex: 'Ist es weit?', exEn: '멀어요?' },
  { ko: 'nah', en: 'near (가까운)', pos: 'adj', ex: 'Der Laden ist ganz nah.', exEn: '가게가 아주 가까워요.' },

  // ---------- Häufige kleine Wörter (die man wirklich abfragen kann) ----------
  { ko: 'und', en: 'and (그리고)', pos: 'other', ex: 'Brot und Käse.', exEn: '빵과 치즈.' },
  { ko: 'aber', en: 'but (하지만)', pos: 'other', ex: 'Ich bin müde, aber glücklich.', exEn: '저는 피곤하지만 행복해요.' },
  { ko: 'oder', en: 'or (또는)', pos: 'other', ex: 'Tee oder Kaffee?', exEn: '차 아니면 커피?' },
  { ko: 'weil', en: 'because (왜냐하면)', pos: 'other', ex: 'Ich bleibe, weil es regnet.', exEn: '비가 와서 집에 있어요.' },
  { ko: 'wenn', en: 'if, when (만약, ~할 때)', pos: 'other', ex: 'Wenn du willst, komme ich.', exEn: '원하시면 갈게요.' },
  { ko: 'auch', en: 'also, too (~도)', pos: 'adv', ex: 'Ich komme auch mit.', exEn: '저도 같이 갈게요.' },
  { ko: 'nicht', en: 'not (아니다)', pos: 'adv', ex: 'Ich weiß es nicht.', exEn: '저는 몰라요.' },
  { ko: 'sehr', en: 'very (아주)', pos: 'adv', ex: 'Das ist sehr gut.', exEn: '아주 좋아요.' },
  { ko: 'mehr', en: 'more (더)', pos: 'adv', ex: 'Ich möchte mehr.', exEn: '더 주세요.' },
  { ko: 'immer', en: 'always (항상)', pos: 'adv', ex: 'Er kommt immer zu spät.', exEn: '그는 항상 늦게 와요.' },
  { ko: 'nie', en: 'never (절대 안)', pos: 'adv', ex: 'Ich trinke nie Alkohol.', exEn: '저는 술을 안 마셔요.' },
  { ko: 'oft', en: 'often (자주)', pos: 'adv', ex: 'Wir treffen uns oft.', exEn: '우리는 자주 만나요.' },
  { ko: 'manchmal', en: 'sometimes (가끔)', pos: 'adv', ex: 'Manchmal koche ich.', exEn: '가끔 요리해요.' },
  { ko: 'jetzt', en: 'now (지금)', pos: 'adv', ex: 'Ich muss jetzt gehen.', exEn: '저는 지금 가야 해요.' },
  { ko: 'heute', en: 'today (오늘)', pos: 'adv', ex: 'Heute ist Montag.', exEn: '오늘은 월요일이에요.' },
  { ko: 'morgen', en: 'tomorrow (내일)', pos: 'adv', ex: 'Bis morgen!', exEn: '내일 봐요!' },
  { ko: 'gestern', en: 'yesterday (어제)', pos: 'adv', ex: 'Gestern war ich müde.', exEn: '어제는 피곤했어요.' },
  { ko: 'hier', en: 'here (여기)', pos: 'adv', ex: 'Ich bin hier.', exEn: '저 여기 있어요.' },
  { ko: 'dort', en: 'there (저기)', pos: 'adv', ex: 'Das Buch liegt dort.', exEn: '책이 저기 있어요.' },
  { ko: 'wieder', en: 'again (다시)', pos: 'adv', ex: 'Sag das bitte wieder.', exEn: '다시 말해 주세요.' },
  { ko: 'schon', en: 'already (벌써)', pos: 'adv', ex: 'Bist du schon da?', exEn: '벌써 왔어요?' },
  { ko: 'noch', en: 'still, yet (아직)', pos: 'adv', ex: 'Ich bin noch nicht fertig.', exEn: '아직 안 끝났어요.' },
  { ko: 'nur', en: 'only (단지)', pos: 'adv', ex: 'Ich habe nur zehn Euro.', exEn: '십 유로밖에 없어요.' },
  { ko: 'fast', en: 'almost (거의)', pos: 'adv', ex: 'Ich bin fast fertig.', exEn: '거의 다 했어요.' },
  { ko: 'vielleicht', en: 'maybe (아마도)', pos: 'adv', ex: 'Vielleicht regnet es.', exEn: '아마 비가 올 거예요.' },
  { ko: 'wirklich', en: 'really (정말로)', pos: 'adv', ex: 'Das ist wirklich gut.', exEn: '정말 좋아요.' },
  { ko: 'natürlich', en: 'of course (물론)', pos: 'adv', ex: 'Natürlich helfe ich dir.', exEn: '물론 도와줄게요.' },
  { ko: 'gern', en: 'gladly, to like doing (기꺼이)', pos: 'adv', ex: 'Ich koche gern.', exEn: '저는 요리를 좋아해요.' },
  { ko: 'zusammen', en: 'together (같이)', pos: 'adv', ex: 'Wir gehen zusammen.', exEn: '우리는 같이 가요.' },
  { ko: 'allein', en: 'alone (혼자)', pos: 'adv', ex: 'Ich wohne allein.', exEn: '저는 혼자 살아요.' },
  { ko: 'endlich', en: 'finally (드디어)', pos: 'adv', ex: 'Endlich bist du da!', exEn: '드디어 왔네요!' },
  { ko: 'sofort', en: 'immediately (바로)', pos: 'adv', ex: 'Ich komme sofort.', exEn: '바로 갈게요.' },
  { ko: 'bald', en: 'soon (곧)', pos: 'adv', ex: 'Bis bald!', exEn: '곧 봐요!' },
  { ko: 'genug', en: 'enough (충분히)', pos: 'adv', ex: 'Das ist genug.', exEn: '충분해요.' },
  { ko: 'zuerst', en: 'first (먼저)', pos: 'adv', ex: 'Zuerst essen wir.', exEn: '먼저 밥 먹어요.' },
  { ko: 'dann', en: 'then (그다음)', pos: 'adv', ex: 'Dann gehen wir.', exEn: '그다음에 가요.' },
  { ko: 'deshalb', en: 'therefore (그래서)', pos: 'adv', ex: 'Es regnet, deshalb bleibe ich.', exEn: '비가 와서 집에 있어요.' },
  { ko: 'trotzdem', en: 'nevertheless (그래도)', pos: 'adv', ex: 'Es regnet, trotzdem gehe ich.', exEn: '비가 와도 갈게요.' },

  // ---------- Fragewörter ----------
  { ko: 'wer', en: 'who (누구)', pos: 'other', ex: 'Wer ist das?', exEn: '저 사람 누구예요?' },
  { ko: 'was', en: 'what (무엇)', pos: 'other', ex: 'Was machst du?', exEn: '뭐 해요?' },
  { ko: 'wo', en: 'where (어디)', pos: 'other', ex: 'Wo wohnst du?', exEn: '어디에 살아요?' },
  { ko: 'wann', en: 'when (언제)', pos: 'other', ex: 'Wann kommst du?', exEn: '언제 와요?' },
  { ko: 'warum', en: 'why (왜)', pos: 'other', ex: 'Warum nicht?', exEn: '왜 안 돼요?' },
  { ko: 'wie', en: 'how (어떻게)', pos: 'other', ex: 'Wie geht es dir?', exEn: '어떻게 지내요?' },

  // ---------- Nützliche Sätze ----------
  { ko: 'Wie geht es dir?', en: 'How are you? (어떻게 지내요?)', pos: 'phrase', ex: 'Hallo, wie geht es dir?', exEn: '안녕, 어떻게 지내요?' },
  { ko: 'Ich verstehe nicht.', en: "I don't understand. (이해가 안 돼요.)", pos: 'phrase', ex: 'Entschuldigung, ich verstehe nicht.', exEn: '죄송해요, 이해가 안 돼요.' },
  { ko: 'Können Sie das wiederholen?', en: 'Could you repeat that? (다시 말해 주시겠어요?)', pos: 'phrase', ex: 'Bitte, können Sie das wiederholen?', exEn: '다시 말해 주시겠어요?' },
  { ko: 'Was bedeutet das?', en: 'What does that mean? (그게 무슨 뜻이에요?)', pos: 'phrase', ex: 'Entschuldigung, was bedeutet das?', exEn: '죄송한데, 그게 무슨 뜻이에요?' },
  { ko: 'Wie viel kostet das?', en: 'How much is it? (얼마예요?)', pos: 'phrase', ex: 'Wie viel kostet das Brot?', exEn: '빵이 얼마예요?' },
  { ko: 'Es tut mir leid.', en: "I'm sorry. (죄송해요.)", pos: 'phrase', ex: 'Es tut mir leid, ich bin spät.', exEn: '늦어서 죄송해요.' },
  { ko: 'Vielen Dank!', en: 'Thank you very much! (정말 고마워요!)', pos: 'phrase', ex: 'Vielen Dank für die Hilfe!', exEn: '도와줘서 정말 고마워요!' },
  { ko: 'Guten Appetit!', en: 'Enjoy your meal! (맛있게 드세요!)', pos: 'phrase', ex: 'Guten Appetit zusammen!', exEn: '다 같이 맛있게 드세요!' },
]
