/* ============================================================
   NACHZIEHSTAPEL — KOREANISCH (für Franz)

   Sortiert nach HÄUFIGKEIT, häufigstes zuerst. Grundlage ist mein
   Wissen über koreanische Häufigkeitslisten (국립국어원 u. ä.).
   Die Größenordnung stimmt — die exakte Rangfolge Platz für Platz
   ist eine Näherung.

   Felder:
     ko    koreanisches Wort (Verben/Adjektive in der Grundform)
     en    englische Bedeutung
     ex    kurzer Beispielsatz
     exEn  Übersetzung des Beispiels

   Bewusst NICHT drin:
   - Partikeln (은/는, 이/가, 을/를, 에, 에서 …). Sie stehen ganz
     oben in jeder Häufigkeitsliste, sind aber Grammatik: "Was
     heißt 은?" ist keine sinnvolle Karteikarte.
   - Zahlwörter — die stecken schon im Zahlen-Blatt und in der
     Zahl des Tages.

   Die Duplikat-Sperre in storage.js vergleicht exakte Zeichen-
   ketten, deshalb stehen Verben und Adjektive einheitlich in der
   Wörterbuchform auf -다.
   ============================================================ */
export const koreanPool = [
  // ---------- Die absoluten Kernwörter ----------
  { ko: '하다', en: 'to do', ex: '뭐 하고 있어요?', exEn: 'What are you doing?' },
  { ko: '있다', en: 'to exist, to have', ex: '시간이 있어요?', exEn: 'Do you have time?' },
  { ko: '없다', en: 'to not exist, to not have', ex: '돈이 없어요.', exEn: 'I have no money.' },
  { ko: '되다', en: 'to become', ex: '의사가 되고 싶어요.', exEn: 'I want to become a doctor.' },
  { ko: '보다', en: 'to see, to watch', ex: '영화를 봐요.', exEn: 'I watch a movie.' },
  { ko: '주다', en: 'to give', ex: '이거 주세요.', exEn: 'Please give me this.' },
  { ko: '가다', en: 'to go', ex: '집에 가요.', exEn: 'I am going home.' },
  { ko: '오다', en: 'to come', ex: '친구가 와요.', exEn: 'A friend is coming.' },
  { ko: '알다', en: 'to know', ex: '저는 알아요.', exEn: 'I know.' },
  { ko: '모르다', en: 'to not know', ex: '잘 모르겠어요.', exEn: "I don't really know." },
  { ko: '말하다', en: 'to speak, to say', ex: '천천히 말해 주세요.', exEn: 'Please speak slowly.' },
  { ko: '생각하다', en: 'to think', ex: '저도 그렇게 생각해요.', exEn: 'I think so too.' },
  { ko: '먹다', en: 'to eat', ex: '점심을 먹었어요.', exEn: 'I ate lunch.' },
  { ko: '마시다', en: 'to drink', ex: '물을 마셔요.', exEn: 'I drink water.' },
  { ko: '자다', en: 'to sleep', ex: '일찍 자요.', exEn: 'I go to bed early.' },
  { ko: '살다', en: 'to live', ex: '서울에 살아요.', exEn: 'I live in Seoul.' },
  { ko: '만들다', en: 'to make', ex: '음식을 만들어요.', exEn: 'I make food.' },
  { ko: '받다', en: 'to receive', ex: '선물을 받았어요.', exEn: 'I received a present.' },
  { ko: '쓰다', en: 'to write, to use', ex: '편지를 써요.', exEn: 'I write a letter.' },
  { ko: '읽다', en: 'to read', ex: '책을 읽어요.', exEn: 'I read a book.' },
  { ko: '듣다', en: 'to listen, to hear', ex: '음악을 들어요.', exEn: 'I listen to music.' },
  { ko: '만나다', en: 'to meet', ex: '내일 만나요.', exEn: "Let's meet tomorrow." },
  { ko: '기다리다', en: 'to wait', ex: '잠깐 기다려 주세요.', exEn: 'Please wait a moment.' },
  { ko: '시작하다', en: 'to start', ex: '지금 시작해요.', exEn: 'We start now.' },
  { ko: '끝나다', en: 'to end', ex: '수업이 끝났어요.', exEn: 'The class ended.' },
  { ko: '나오다', en: 'to come out', ex: '밖으로 나와요.', exEn: 'Come outside.' },
  { ko: '들어가다', en: 'to go in, to enter', ex: '안으로 들어가요.', exEn: 'Go inside.' },
  { ko: '앉다', en: 'to sit', ex: '여기 앉으세요.', exEn: 'Please sit here.' },
  { ko: '서다', en: 'to stand', ex: '줄을 서요.', exEn: 'Stand in line.' },
  { ko: '걷다', en: 'to walk', ex: '공원을 걸어요.', exEn: 'I walk in the park.' },
  { ko: '뛰다', en: 'to run', ex: '아이가 뛰어요.', exEn: 'The child is running.' },
  { ko: '타다', en: 'to ride, to take transport', ex: '버스를 타요.', exEn: 'I take the bus.' },
  { ko: '내리다', en: 'to get off, to come down', ex: '여기서 내려요.', exEn: 'I get off here.' },
  { ko: '사다', en: 'to buy', ex: '빵을 사요.', exEn: 'I buy bread.' },
  { ko: '팔다', en: 'to sell', ex: '차를 팔아요.', exEn: 'I sell a car.' },
  { ko: '일하다', en: 'to work', ex: '회사에서 일해요.', exEn: 'I work at a company.' },
  { ko: '공부하다', en: 'to study', ex: '한국어를 공부해요.', exEn: 'I study Korean.' },
  { ko: '배우다', en: 'to learn', ex: '요리를 배워요.', exEn: 'I learn cooking.' },
  { ko: '가르치다', en: 'to teach', ex: '선생님이 가르쳐요.', exEn: 'The teacher teaches.' },
  { ko: '좋아하다', en: 'to like', ex: '커피를 좋아해요.', exEn: 'I like coffee.' },
  { ko: '사랑하다', en: 'to love', ex: '가족을 사랑해요.', exEn: 'I love my family.' },
  { ko: '싫어하다', en: 'to dislike', ex: '비를 싫어해요.', exEn: 'I dislike rain.' },
  { ko: '원하다', en: 'to want', ex: '무엇을 원해요?', exEn: 'What do you want?' },
  { ko: '필요하다', en: 'to need', ex: '도움이 필요해요.', exEn: 'I need help.' },
  { ko: '찾다', en: 'to look for, to find', ex: '열쇠를 찾아요.', exEn: 'I am looking for the key.' },
  { ko: '묻다', en: 'to ask', ex: '길을 물어요.', exEn: 'I ask for directions.' },
  { ko: '대답하다', en: 'to answer', ex: '질문에 대답해요.', exEn: 'I answer the question.' },
  { ko: '전화하다', en: 'to call on the phone', ex: '나중에 전화할게요.', exEn: 'I will call later.' },
  { ko: '보내다', en: 'to send', ex: '문자를 보냈어요.', exEn: 'I sent a text.' },
  { ko: '열다', en: 'to open', ex: '창문을 열어요.', exEn: 'I open the window.' },
  { ko: '닫다', en: 'to close', ex: '문을 닫아 주세요.', exEn: 'Please close the door.' },
  { ko: '놓다', en: 'to put down', ex: '가방을 놓으세요.', exEn: 'Put the bag down.' },
  { ko: '들다', en: 'to lift, to hold', ex: '가방을 들어요.', exEn: 'I carry the bag.' },
  { ko: '입다', en: 'to wear clothes', ex: '코트를 입어요.', exEn: 'I wear a coat.' },
  { ko: '벗다', en: 'to take off', ex: '신발을 벗으세요.', exEn: 'Please take off your shoes.' },
  { ko: '씻다', en: 'to wash', ex: '손을 씻어요.', exEn: 'I wash my hands.' },
  { ko: '청소하다', en: 'to clean', ex: '방을 청소해요.', exEn: 'I clean the room.' },
  { ko: '요리하다', en: 'to cook', ex: '저녁을 요리해요.', exEn: 'I cook dinner.' },
  { ko: '쉬다', en: 'to rest', ex: '주말에 쉬어요.', exEn: 'I rest on the weekend.' },
  { ko: '놀다', en: 'to play, to hang out', ex: '친구와 놀아요.', exEn: 'I hang out with a friend.' },
  { ko: '웃다', en: 'to laugh, to smile', ex: '많이 웃었어요.', exEn: 'I laughed a lot.' },
  { ko: '울다', en: 'to cry', ex: '아기가 울어요.', exEn: 'The baby is crying.' },
  { ko: '느끼다', en: 'to feel', ex: '행복을 느껴요.', exEn: 'I feel happy.' },
  { ko: '잊다', en: 'to forget', ex: '이름을 잊었어요.', exEn: 'I forgot the name.' },
  { ko: '기억하다', en: 'to remember', ex: '아직 기억해요.', exEn: 'I still remember.' },
  { ko: '준비하다', en: 'to prepare', ex: '시험을 준비해요.', exEn: 'I prepare for the exam.' },
  { ko: '도와주다', en: 'to help', ex: '좀 도와주세요.', exEn: 'Please help me.' },
  { ko: '가지다', en: 'to have, to hold', ex: '우산을 가지고 왔어요.', exEn: 'I brought an umbrella.' },
  { ko: '들어오다', en: 'to come in', ex: '들어오세요.', exEn: 'Please come in.' },

  // ---------- Häufige Substantive ----------
  { ko: '사람', en: 'person', ex: '저 사람은 누구예요?', exEn: 'Who is that person?' },
  { ko: '일', en: 'work, matter, day', ex: '오늘 일이 많아요.', exEn: 'I have a lot of work today.' },
  { ko: '때', en: 'time, moment', ex: '어릴 때 좋아했어요.', exEn: 'I liked it when I was young.' },
  { ko: '말', en: 'words, speech', ex: '그 말이 맞아요.', exEn: 'That is right.' },
  { ko: '집', en: 'house, home', ex: '집에 가고 싶어요.', exEn: 'I want to go home.' },
  { ko: '시간', en: 'time, hour', ex: '시간이 없어요.', exEn: 'I have no time.' },
  { ko: '오늘', en: 'today', ex: '오늘 뭐 해요?', exEn: 'What are you doing today?' },
  { ko: '내일', en: 'tomorrow', ex: '내일 봐요.', exEn: 'See you tomorrow.' },
  { ko: '어제', en: 'yesterday', ex: '어제는 바빴어요.', exEn: 'I was busy yesterday.' },
  { ko: '지금', en: 'now', ex: '지금 어디예요?', exEn: 'Where are you now?' },
  { ko: '나라', en: 'country', ex: '어느 나라에서 왔어요?', exEn: 'Which country are you from?' },
  { ko: '친구', en: 'friend', ex: '친구를 만나요.', exEn: 'I meet a friend.' },
  { ko: '학교', en: 'school', ex: '학교에 다녀요.', exEn: 'I go to school.' },
  { ko: '학생', en: 'student', ex: '저는 학생이에요.', exEn: 'I am a student.' },
  { ko: '회사', en: 'company', ex: '회사가 멀어요.', exEn: 'The company is far.' },
  { ko: '돈', en: 'money', ex: '돈이 필요해요.', exEn: 'I need money.' },
  { ko: '물', en: 'water', ex: '물 좀 주세요.', exEn: 'Some water, please.' },
  { ko: '밥', en: 'rice, meal', ex: '밥 먹었어요?', exEn: 'Have you eaten?' },
  { ko: '음식', en: 'food', ex: '음식이 맛있어요.', exEn: 'The food is delicious.' },
  { ko: '커피', en: 'coffee', ex: '커피 한 잔 주세요.', exEn: 'One coffee, please.' },
  { ko: '책', en: 'book', ex: '책을 읽어요.', exEn: 'I read a book.' },
  { ko: '영화', en: 'movie', ex: '영화를 봤어요.', exEn: 'I watched a movie.' },
  { ko: '노래', en: 'song', ex: '노래를 불러요.', exEn: 'I sing a song.' },
  { ko: '음악', en: 'music', ex: '음악을 들어요.', exEn: 'I listen to music.' },
  { ko: '이름', en: 'name', ex: '이름이 뭐예요?', exEn: 'What is your name?' },
  { ko: '말씀', en: 'words (polite)', ex: '말씀 감사합니다.', exEn: 'Thank you for your words.' },
  { ko: '문제', en: 'problem, question', ex: '문제가 있어요.', exEn: 'There is a problem.' },
  { ko: '생각', en: 'thought, idea', ex: '좋은 생각이에요.', exEn: 'That is a good idea.' },
  { ko: '이야기', en: 'story, talk', ex: '이야기를 들었어요.', exEn: 'I heard the story.' },
  { ko: '전화', en: 'telephone', ex: '전화가 왔어요.', exEn: 'There was a call.' },
  { ko: '길', en: 'road, way', ex: '길을 잃었어요.', exEn: 'I got lost.' },
  { ko: '차', en: 'car, tea', ex: '차가 막혀요.', exEn: 'The traffic is heavy.' },
  { ko: '방', en: 'room', ex: '방이 깨끗해요.', exEn: 'The room is clean.' },
  { ko: '문', en: 'door', ex: '문이 열려 있어요.', exEn: 'The door is open.' },
  { ko: '창문', en: 'window', ex: '창문을 닫았어요.', exEn: 'I closed the window.' },
  { ko: '옷', en: 'clothes', ex: '옷을 샀어요.', exEn: 'I bought clothes.' },
  { ko: '신발', en: 'shoes', ex: '신발이 편해요.', exEn: 'The shoes are comfortable.' },
  { ko: '가방', en: 'bag', ex: '가방이 무거워요.', exEn: 'The bag is heavy.' },
  { ko: '날씨', en: 'weather', ex: '날씨가 좋아요.', exEn: 'The weather is nice.' },
  { ko: '하늘', en: 'sky', ex: '하늘이 파래요.', exEn: 'The sky is blue.' },
  { ko: '비', en: 'rain', ex: '비가 와요.', exEn: 'It is raining.' },
  { ko: '눈', en: 'snow, eye', ex: '눈이 와요.', exEn: 'It is snowing.' },
  { ko: '바람', en: 'wind', ex: '바람이 불어요.', exEn: 'The wind is blowing.' },
  { ko: '아침', en: 'morning, breakfast', ex: '아침에 일어나요.', exEn: 'I get up in the morning.' },
  { ko: '점심', en: 'lunch, midday', ex: '점심 먹었어요?', exEn: 'Did you have lunch?' },
  { ko: '저녁', en: 'evening, dinner', ex: '저녁에 만나요.', exEn: "Let's meet in the evening." },
  { ko: '주말', en: 'weekend', ex: '주말에 뭐 해요?', exEn: 'What do you do on the weekend?' },
  { ko: '올해', en: 'this year', ex: '올해는 바빠요.', exEn: 'This year is busy.' },
  { ko: '나이', en: 'age', ex: '나이가 어떻게 되세요?', exEn: 'How old are you?' },
  { ko: '자리', en: 'seat, place', ex: '이 자리 비었어요?', exEn: 'Is this seat free?' },
  { ko: '곳', en: 'place', ex: '좋은 곳이에요.', exEn: 'It is a nice place.' },
  { ko: '것', en: 'thing', ex: '이건 제 거예요.', exEn: 'This is mine.' },
  { ko: '수업', en: 'class, lesson', ex: '수업이 재미있어요.', exEn: 'The class is interesting.' },
  { ko: '시험', en: 'exam', ex: '시험이 어려웠어요.', exEn: 'The exam was hard.' },
  { ko: '병원', en: 'hospital', ex: '병원에 가요.', exEn: 'I go to the hospital.' },
  { ko: '약', en: 'medicine, about', ex: '약을 먹어요.', exEn: 'I take medicine.' },
  { ko: '가게', en: 'shop', ex: '가게가 문을 닫았어요.', exEn: 'The shop is closed.' },
  { ko: '지하철', en: 'subway', ex: '지하철을 타요.', exEn: 'I take the subway.' },
  { ko: '버스', en: 'bus', ex: '버스가 늦어요.', exEn: 'The bus is late.' },
  { ko: '공항', en: 'airport', ex: '공항에 도착했어요.', exEn: 'I arrived at the airport.' },
  { ko: '여행', en: 'travel', ex: '여행을 좋아해요.', exEn: 'I like traveling.' },
  { ko: '사진', en: 'photo', ex: '사진을 찍어요.', exEn: 'I take a photo.' },
  { ko: '선물', en: 'present, gift', ex: '선물을 줬어요.', exEn: 'I gave a present.' },
  { ko: '마음', en: 'heart, mind', ex: '마음이 아파요.', exEn: 'My heart hurts.' },
  { ko: '몸', en: 'body', ex: '몸이 안 좋아요.', exEn: 'I do not feel well.' },
  { ko: '기분', en: 'mood, feeling', ex: '기분이 좋아요.', exEn: 'I am in a good mood.' },

  // ---------- Häufige Adjektive (auf -다) ----------
  { ko: '좋다', en: 'to be good', ex: '날씨가 좋아요.', exEn: 'The weather is good.' },
  { ko: '나쁘다', en: 'to be bad', ex: '기분이 나빠요.', exEn: 'I am in a bad mood.' },
  { ko: '크다', en: 'to be big', ex: '집이 커요.', exEn: 'The house is big.' },
  { ko: '작다', en: 'to be small', ex: '방이 작아요.', exEn: 'The room is small.' },
  { ko: '많다', en: 'to be many, a lot', ex: '사람이 많아요.', exEn: 'There are many people.' },
  { ko: '적다', en: 'to be few', ex: '시간이 적어요.', exEn: 'There is little time.' },
  { ko: '길다', en: 'to be long', ex: '머리가 길어요.', exEn: 'The hair is long.' },
  { ko: '짧다', en: 'to be short', ex: '치마가 짧아요.', exEn: 'The skirt is short.' },
  { ko: '높다', en: 'to be high', ex: '산이 높아요.', exEn: 'The mountain is high.' },
  { ko: '낮다', en: 'to be low', ex: '가격이 낮아요.', exEn: 'The price is low.' },
  { ko: '빠르다', en: 'to be fast', ex: '기차가 빨라요.', exEn: 'The train is fast.' },
  { ko: '느리다', en: 'to be slow', ex: '인터넷이 느려요.', exEn: 'The internet is slow.' },
  { ko: '쉽다', en: 'to be easy', ex: '문제가 쉬워요.', exEn: 'The question is easy.' },
  { ko: '어렵다', en: 'to be difficult', ex: '한국어가 어려워요.', exEn: 'Korean is difficult.' },
  { ko: '맛있다', en: 'to be delicious', ex: '이거 정말 맛있어요.', exEn: 'This is really delicious.' },
  { ko: '맛없다', en: 'to taste bad', ex: '음식이 맛없어요.', exEn: 'The food tastes bad.' },
  { ko: '예쁘다', en: 'to be pretty', ex: '꽃이 예뻐요.', exEn: 'The flower is pretty.' },
  { ko: '멋있다', en: 'to be cool, stylish', ex: '정말 멋있어요.', exEn: 'That is really cool.' },
  { ko: '재미있다', en: 'to be fun, interesting', ex: '영화가 재미있어요.', exEn: 'The movie is fun.' },
  { ko: '재미없다', en: 'to be boring', ex: '책이 재미없어요.', exEn: 'The book is boring.' },
  { ko: '바쁘다', en: 'to be busy', ex: '요즘 바빠요.', exEn: 'I am busy these days.' },
  { ko: '피곤하다', en: 'to be tired', ex: '오늘 피곤해요.', exEn: 'I am tired today.' },
  { ko: '아프다', en: 'to hurt, to be sick', ex: '머리가 아파요.', exEn: 'My head hurts.' },
  { ko: '기쁘다', en: 'to be glad', ex: '만나서 기뻐요.', exEn: 'I am glad to meet you.' },
  { ko: '슬프다', en: 'to be sad', ex: '영화가 슬퍼요.', exEn: 'The movie is sad.' },
  { ko: '행복하다', en: 'to be happy', ex: '저는 행복해요.', exEn: 'I am happy.' },
  { ko: '춥다', en: 'to be cold (weather)', ex: '오늘 추워요.', exEn: 'It is cold today.' },
  { ko: '덥다', en: 'to be hot (weather)', ex: '여름은 더워요.', exEn: 'Summer is hot.' },
  { ko: '따뜻하다', en: 'to be warm', ex: '방이 따뜻해요.', exEn: 'The room is warm.' },
  { ko: '시원하다', en: 'to be cool, refreshing', ex: '바람이 시원해요.', exEn: 'The wind is refreshing.' },
  { ko: '비싸다', en: 'to be expensive', ex: '너무 비싸요.', exEn: 'It is too expensive.' },
  { ko: '싸다', en: 'to be cheap', ex: '이게 더 싸요.', exEn: 'This one is cheaper.' },
  { ko: '새롭다', en: 'to be new', ex: '새로운 일이에요.', exEn: 'It is a new job.' },
  { ko: '같다', en: 'to be the same', ex: '저도 같아요.', exEn: 'I am the same.' },
  { ko: '다르다', en: 'to be different', ex: '생각이 달라요.', exEn: 'My opinion is different.' },
  { ko: '중요하다', en: 'to be important', ex: '이게 제일 중요해요.', exEn: 'This is the most important.' },
  { ko: '괜찮다', en: 'to be okay, fine', ex: '저는 괜찮아요.', exEn: 'I am fine.' },
  { ko: '조용하다', en: 'to be quiet', ex: '여기는 조용해요.', exEn: 'It is quiet here.' },
  { ko: '시끄럽다', en: 'to be noisy', ex: '밖이 시끄러워요.', exEn: 'It is noisy outside.' },
  { ko: '깨끗하다', en: 'to be clean', ex: '방이 깨끗해요.', exEn: 'The room is clean.' },
  { ko: '더럽다', en: 'to be dirty', ex: '손이 더러워요.', exEn: 'My hands are dirty.' },
  { ko: '멀다', en: 'to be far', ex: '집이 멀어요.', exEn: 'Home is far.' },
  { ko: '가깝다', en: 'to be close', ex: '역이 가까워요.', exEn: 'The station is close.' },
  { ko: '무겁다', en: 'to be heavy', ex: '가방이 무거워요.', exEn: 'The bag is heavy.' },
  { ko: '가볍다', en: 'to be light', ex: '가방이 가벼워요.', exEn: 'The bag is light.' },
  { ko: '친절하다', en: 'to be kind', ex: '아주 친절해요.', exEn: 'They are very kind.' },
  { ko: '유명하다', en: 'to be famous', ex: '이 식당은 유명해요.', exEn: 'This restaurant is famous.' },
  { ko: '심심하다', en: 'to be bored', ex: '오늘 심심해요.', exEn: 'I am bored today.' },
  { ko: '배고프다', en: 'to be hungry', ex: '배고파요.', exEn: 'I am hungry.' },
  { ko: '배부르다', en: 'to be full', ex: '배불러요.', exEn: 'I am full.' },

  // ---------- Häufige Adverbien und kleine Wörter ----------
  { ko: '아주', en: 'very', ex: '아주 좋아요.', exEn: 'It is very good.' },
  { ko: '너무', en: 'too, very', ex: '너무 비싸요.', exEn: 'It is too expensive.' },
  { ko: '많이', en: 'a lot', ex: '많이 드세요.', exEn: 'Please eat a lot.' },
  { ko: '조금', en: 'a little', ex: '조금만 주세요.', exEn: 'Just a little, please.' },
  { ko: '잘', en: 'well', ex: '잘 지내요?', exEn: 'Are you doing well?' },
  { ko: '못', en: 'cannot', ex: '저는 못 가요.', exEn: 'I cannot go.' },
  { ko: '안', en: 'not', ex: '저는 안 먹어요.', exEn: 'I do not eat it.' },
  { ko: '다시', en: 'again', ex: '다시 말해 주세요.', exEn: 'Please say it again.' },
  { ko: '또', en: 'again, also', ex: '또 만나요.', exEn: 'See you again.' },
  { ko: '먼저', en: 'first', ex: '먼저 가세요.', exEn: 'Please go first.' },
  { ko: '같이', en: 'together', ex: '같이 가요.', exEn: "Let's go together." },
  { ko: '혼자', en: 'alone', ex: '혼자 살아요.', exEn: 'I live alone.' },
  { ko: '빨리', en: 'quickly', ex: '빨리 오세요.', exEn: 'Please come quickly.' },
  { ko: '천천히', en: 'slowly', ex: '천천히 말해 주세요.', exEn: 'Please speak slowly.' },
  { ko: '항상', en: 'always', ex: '항상 늦어요.', exEn: 'He is always late.' },
  { ko: '가끔', en: 'sometimes', ex: '가끔 만나요.', exEn: 'We meet sometimes.' },
  { ko: '자주', en: 'often', ex: '자주 가요.', exEn: 'I go there often.' },
  { ko: '벌써', en: 'already', ex: '벌써 끝났어요?', exEn: 'Is it already over?' },
  { ko: '아직', en: 'still, not yet', ex: '아직 안 왔어요.', exEn: 'They have not come yet.' },
  { ko: '정말', en: 'really', ex: '정말 고마워요.', exEn: 'Thank you really.' },
  { ko: '진짜', en: 'really (casual)', ex: '진짜 맛있어요!', exEn: 'It is really tasty!' },
  { ko: '물론', en: 'of course', ex: '물론이죠.', exEn: 'Of course.' },
  { ko: '아마', en: 'probably', ex: '아마 올 거예요.', exEn: 'They will probably come.' },
  { ko: '거의', en: 'almost', ex: '거의 다 됐어요.', exEn: 'It is almost done.' },
  { ko: '함께', en: 'together (formal)', ex: '함께 일해요.', exEn: 'We work together.' },
  { ko: '나중에', en: 'later', ex: '나중에 얘기해요.', exEn: "Let's talk later." },
  { ko: '그리고', en: 'and', ex: '밥 그리고 국.', exEn: 'Rice and soup.' },
  { ko: '그런데', en: 'but, by the way', ex: '그런데 왜요?', exEn: 'But why?' },
  { ko: '하지만', en: 'however', ex: '하지만 어려워요.', exEn: 'However, it is difficult.' },
  { ko: '그래서', en: 'so, therefore', ex: '비가 와서 그래서 안 갔어요.', exEn: 'It rained, so I did not go.' },
  { ko: '그러면', en: 'then, in that case', ex: '그러면 내일 만나요.', exEn: 'Then see you tomorrow.' },
  { ko: '왜', en: 'why', ex: '왜 안 왔어요?', exEn: 'Why did you not come?' },
  { ko: '어디', en: 'where', ex: '어디에 가요?', exEn: 'Where are you going?' },
  { ko: '언제', en: 'when', ex: '언제 만나요?', exEn: 'When shall we meet?' },
  { ko: '누구', en: 'who', ex: '저분은 누구예요?', exEn: 'Who is that person?' },
  { ko: '어떻게', en: 'how', ex: '어떻게 가요?', exEn: 'How do I get there?' },
  { ko: '무엇', en: 'what', ex: '이게 무엇이에요?', exEn: 'What is this?' },
  { ko: '얼마', en: 'how much', ex: '이거 얼마예요?', exEn: 'How much is this?' },

  // ---------- Nützliche Sätze ----------
  { ko: '감사합니다', en: 'Thank you', ex: '도와주셔서 감사합니다.', exEn: 'Thank you for helping.' },
  { ko: '죄송합니다', en: 'I am sorry', ex: '늦어서 죄송합니다.', exEn: 'I am sorry for being late.' },
  { ko: '괜찮아요', en: 'It is okay', ex: '괜찮아요, 걱정 마세요.', exEn: 'It is okay, do not worry.' },
  { ko: '잘 모르겠어요', en: 'I am not sure', ex: '저는 잘 모르겠어요.', exEn: 'I am not really sure.' },
  { ko: '다시 말해 주세요', en: 'Please say it again', ex: '천천히 다시 말해 주세요.', exEn: 'Please say it again slowly.' },
  { ko: '얼마예요?', en: 'How much is it?', ex: '이거 얼마예요?', exEn: 'How much is this?' },
  { ko: '어디에 있어요?', en: 'Where is it?', ex: '화장실이 어디에 있어요?', exEn: 'Where is the toilet?' },
  { ko: '잘 먹겠습니다', en: 'Said before eating', ex: '잘 먹겠습니다!', exEn: 'Thanks for the meal!' },
]
